<?php $d=$document; $name=trim((string)($d['workspace_name']??'Byznio')); $type=$d['doc_type']==='offer'?'Nabídka':'Faktura'; ?>
<div style="min-height:100vh;background:#f5f8fc;padding:32px 16px;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#10213f">
  <div style="max-width:760px;margin:0 auto">
    <div style="display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:18px;flex-wrap:wrap">
      <div><div style="font-size:12px;color:#6c7890;font-weight:800;text-transform:uppercase;letter-spacing:.08em">Byznio · veřejný doklad</div><h1 style="margin:5px 0 0;font-size:30px;letter-spacing:-.03em"><?=\App\Core\View::e($type)?> č. <?=\App\Core\View::e($d['doc_number'])?></h1></div>
      <div style="font-weight:800;color:#0c2b5a"><?=\App\Core\View::e($name)?></div>
    </div>
    <div style="background:#fff;border:1px solid #e5eaf2;border-radius:20px;padding:22px;box-shadow:0 12px 34px rgba(16,33,63,.07)">
      <div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:22px">
        <div style="background:#f7f9fc;border-radius:14px;padding:14px"><div style="font-size:11px;color:#6c7890;text-transform:uppercase;font-weight:800">Vystaveno</div><strong><?=\App\Core\View::e($d['issue_date'])?></strong></div>
        <div style="background:#f7f9fc;border-radius:14px;padding:14px"><div style="font-size:11px;color:#6c7890;text-transform:uppercase;font-weight:800">Splatnost</div><strong><?=\App\Core\View::e($d['due_date'])?></strong></div>
        <div style="background:#f7f9fc;border-radius:14px;padding:14px"><div style="font-size:11px;color:#6c7890;text-transform:uppercase;font-weight:800">DUZP</div><strong><?=\App\Core\View::e($d['tax_date']??$d['issue_date'])?></strong></div><div style="background:#f7f9fc;border-radius:14px;padding:14px"><div style="font-size:11px;color:#6c7890;text-transform:uppercase;font-weight:800">Celkem</div><strong><?=\App\Core\View::money($d['total_with_vat'])?> <?=\App\Core\View::e($d['currency']??'CZK')?></strong></div>
      </div>
      <div style="margin:14px 0;color:#5c6c83;font-size:13px">DPH: <?=\App\Core\View::money($d['total_vat'])?> · Základ: <?=\App\Core\View::money($d['total_without_vat'])?> · Režim: <?=\App\Core\View::e($d['tax_regime']??'standard')?></div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:left;padding:10px;border-bottom:1px solid #e5eaf2;font-size:11px;color:#6c7890;text-transform:uppercase">Položka</th><th style="text-align:right;padding:10px;border-bottom:1px solid #e5eaf2;font-size:11px;color:#6c7890;text-transform:uppercase">Množství</th><th style="text-align:right;padding:10px;border-bottom:1px solid #e5eaf2;font-size:11px;color:#6c7890;text-transform:uppercase">Cena</th></tr></thead><tbody><?php foreach($d['_items'] as $it): ?><tr><td style="padding:12px 10px;border-bottom:1px solid #eef1f5"><strong><?=\App\Core\View::e($it['name'])?></strong><?php if(!empty($it['description'])): ?><div style="font-size:13px;color:#6c7890"><?=\App\Core\View::e($it['description'])?></div><?php endif; ?></td><td style="padding:12px 10px;border-bottom:1px solid #eef1f5;text-align:right"><?=\App\Core\View::e($it['quantity'])?> <?=\App\Core\View::e($it['unit'])?></td><td style="padding:12px 10px;border-bottom:1px solid #eef1f5;text-align:right"><?=\App\Core\View::money($it['line_total'])?></td></tr><?php endforeach; ?></tbody></table></div>
      <div style="display:flex;justify-content:flex-end;margin-top:18px;font-size:22px;font-weight:900">Celkem <?=\App\Core\View::money($d['total_with_vat'])?></div>
      <?php if($d['doc_type']==='offer'): ?>
        <div style="margin-top:24px;padding-top:20px;border-top:1px solid #e5eaf2"><div style="font-weight:800;margin-bottom:10px">Odpověď na nabídku</div><?php if($d['status']==='accepted'): ?><div style="color:#0a9b64;font-weight:800;margin-bottom:12px">Nabídka je schválena.</div><?php elseif($d['status']==='rejected'): ?><div style="color:#c2413b;font-weight:800;margin-bottom:12px">Nabídka byla odmítnuta.</div><?php endif; ?><div style="display:flex;gap:10px;flex-wrap:wrap"><form method="post" action="/d/<?=\App\Core\View::e($d['_token'])?>/respond"><input type="hidden" name="status" value="accepted"><button type="submit" style="border:0;background:#1677ee;color:#fff;padding:12px 18px;border-radius:11px;font-weight:800;cursor:pointer">Souhlasím</button></form><form method="post" action="/d/<?=\App\Core\View::e($d['_token'])?>/respond"><input type="hidden" name="status" value="rejected"><button type="submit" style="border:1px solid #d6deea;background:#fff;color:#10213f;padding:12px 18px;border-radius:11px;font-weight:800;cursor:pointer">Nemám zájem</button></form></div><p style="font-size:12px;color:#6c7890;margin-bottom:0">Odpověď se uloží k nabídce jako akce zákazníka.</p></div>
      <?php elseif($d['doc_type']==='invoice' && $d['status']!=='cancelled' && $d['payment_status']!=='paid'): ?>
        <div style="margin-top:24px;padding-top:20px;border-top:1px solid #e5eaf2"><div style="font-weight:800;margin-bottom:10px">Úhrada faktury</div><form method="post" action="/d/<?=\App\Core\View::e($d['_token'])?>/pay"><button type="submit" style="border:0;background:#1677ee;color:#fff;padding:12px 22px;border-radius:11px;font-weight:800;cursor:pointer"><?=!empty($gopay_connected)?'Zaplatit přes GoPay':'Zobrazit QR platbu'?></button></form></div>
      <?php else: ?><div style="margin-top:24px;padding-top:20px;border-top:1px solid #e5eaf2;color:#0a9b64;font-weight:800">Faktura je uhrazena.</div><?php endif; ?>
    </div>
    <div style="text-align:center;color:#6c7890;font-size:12px;margin-top:18px">Tento odkaz je zabezpečen jedinečným náhodným tokenem.</div>
  </div>
</div>
<style>@media(max-width:560px){h1{font-size:24px!important}.public-grid{grid-template-columns:1fr}}</style>
