<?php
namespace App\Services;
use PDO;
final class DocumentService {
 public static function nextNumber(PDO $db,int $wid,string $type): string { $prefix=['invoice'=>'FV','offer'=>'CN','order'=>'OBJ','proforma'=>'ZAL','credit'=>'DOB'][$type]??'DOC';$q=$db->prepare('SELECT next_number FROM document_series WHERE workspace_id=? AND doc_type=?');$q->execute([$wid,$type]);$n=$q->fetchColumn();if($n===false){$n=1;$db->prepare('INSERT INTO document_series(workspace_id,doc_type,prefix,next_number) VALUES(?,?,?,?)')->execute([$wid,$type,$prefix,2]);}else{$db->prepare('UPDATE document_series SET next_number=next_number+1 WHERE workspace_id=? AND doc_type=?')->execute([$wid,$type]);}return $prefix.'-'.date('Y').'-'.str_pad((string)$n,5,'0',STR_PAD_LEFT); }
 public static function paid(PDO $db,int $wid,int $docId):float{$s=$db->prepare('SELECT COALESCE(SUM(amount),0) FROM payments WHERE workspace_id=? AND document_id=?');$s->execute([$wid,$docId]);return (float)$s->fetchColumn();}
 public static function refreshPaymentStatus(PDO $db,int $wid,int $docId):void{$s=$db->prepare('SELECT total_with_vat FROM documents WHERE id=? AND workspace_id=?');$s->execute([$docId,$wid]);$total=(float)$s->fetchColumn();$paid=self::paid($db,$wid,$docId);$status=$paid<=0?'unpaid':($paid+0.01>=$total?'paid':'partially_paid');$db->prepare('UPDATE documents SET payment_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?')->execute([$status,$docId,$wid]);}
 public static function createFromTemplate(PDO $db,array $r):?int { $t=json_decode($r['template_json']??'',true);if(!$t)return null;$wid=(int)$r['workspace_id'];$cid=(int)$r['customer_id'];$type='invoice';$n='FV-'.date('Y').'-'.str_pad((string)((int)$db->query("SELECT COALESCE(MAX(id),0)+1 FROM documents")->fetchColumn()),5,'0',STR_PAD_LEFT);$items=$t['items']??[];$sub=$vat=0;foreach($items as $it){$line=round((float)$it['quantity']*(float)$it['unit_price'],2);$sub+=$line;$vat+=round($line*(float)($it['vat_rate']??21)/100,2);} $db->prepare('INSERT INTO documents(workspace_id,doc_type,doc_number,variable_symbol,customer_id,status,payment_status,issue_date,due_date,total_without_vat,total_vat,total_with_vat,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$wid,$type,$n,preg_replace('/\D/','',$n),$cid,'issued','unpaid',date('Y-m-d'),date('Y-m-d',strtotime('+14 days')),$sub,$vat,$sub+$vat,null]);$id=(int)$db->lastInsertId();$st=$db->prepare('INSERT INTO document_items(document_id,name,quantity,unit,unit_price,vat_rate,line_total) VALUES(?,?,?,?,?,?,?)');foreach($items as $it)$st->execute([$id,$it['name'],(float)$it['quantity'],$it['unit']??'ks',(float)$it['unit_price'],(float)($it['vat_rate']??21),round((float)$it['quantity']*(float)$it['unit_price'],2)]);return $id;}
}
