<?php
namespace App\Services;
use App\Core\Env;
final class MailerService {
 private static string $lastError='';
 private static function shell(string $content,string $name,?string $actionUrl=null,?string $logoPath=null,?int $workspaceId=null,?string $eyebrow=null,?string $headline=null,?array $facts=[]):string{
  $app=rtrim(Env::get('APP_URL','https://byznio.cz'),'/');$logo=$app.'/assets/byznio-logo.svg';if($logoPath&&$workspaceId){$token=hash_hmac('sha256',(string)$workspaceId,(string)Env::get('APP_KEY',''));$logo=$app.'/mail/logo/'.(int)$workspaceId.'?token='.$token;}
  $factsHtml='';foreach($facts as $k=>$v)$factsHtml.='<tr><td style="padding:10px 0;color:#64748b;font-size:13px">'.htmlspecialchars($k,ENT_QUOTES,'UTF-8').'</td><td style="padding:10px 0;text-align:right;font-weight:800;color:#0f172a">'.htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8').'</td></tr>';
  $button=$actionUrl?'<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0"><tr><td style="border-radius:10px;background:#2563eb"><a href="'.htmlspecialchars($actionUrl,ENT_QUOTES,'UTF-8').'" style="display:inline-block;padding:13px 20px;color:#fff;text-decoration:none;font-weight:700">Otevřít v Byzniu</a></td></tr></table>':'';
  $h=$headline?'<h1 style="margin:0 0 10px;font-size:25px;line-height:1.25;color:#0f172a">'.htmlspecialchars($headline,ENT_QUOTES,'UTF-8').'</h1>':'';$e=$eyebrow?'<div style="font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#2563eb;margin-bottom:8px">'.htmlspecialchars($eyebrow,ENT_QUOTES,'UTF-8').'</div>':'';
  $factsBlock=$factsHtml?'<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;margin:22px 0">'.$factsHtml.'</table>':'';
  return '<!doctype html><html><body style="margin:0;background:#f1f5f9;font-family:Arial,Helvetica,sans-serif;color:#334155"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="620" cellpadding="0" cellspacing="0" style="max-width:620px;width:100%"><tr><td style="background:#0b1f3a;padding:22px 28px;border-radius:16px 16px 0 0"><img src="'.htmlspecialchars($logo,ENT_QUOTES,'UTF-8').'" alt="Byznio" width="132" style="display:block;max-width:132px;height:auto"></td></tr><tr><td style="background:#fff;padding:32px 30px;border:1px solid #e2e8f0;border-top:0;border-radius:0 0 16px 16px">'.$e.$h.'<div style="font-size:15px;line-height:1.7">'.$content.'</div>'.$factsBlock.$button.'<div style="margin-top:30px;padding-top:18px;border-top:1px solid #e2e8f0;font-size:13px;color:#64748b">S pozdravem,<br><strong style="color:#0f172a">'.htmlspecialchars($name,ENT_QUOTES,'UTF-8').'</strong><br><img src="'.htmlspecialchars($logo,ENT_QUOTES,'UTF-8').'" alt="Byznio" width="90" style="display:block;margin-top:10px;max-height:30px;width:auto"><div style="margin-top:10px;font-size:11px">Odesláno prostřednictvím Byznio.</div></div></td></tr></table></td></tr></table></body></html>';
 }
 private static function html(string $body,string $name,?string $actionUrl=null,?string $logoPath=null,?int $workspaceId=null):string{return self::shell(nl2br(htmlspecialchars($body,ENT_QUOTES,'UTF-8')),$name,$actionUrl,$logoPath,$workspaceId,'Byznio');}
 public static function reportHtml(string $htmlBody,string $name,?string $actionUrl=null,?string $logoPath=null,?int $workspaceId=null):string{return self::shell($htmlBody,$name,$actionUrl,$logoPath,$workspaceId,'Byznio report');}
 public static function htmlForLog(string $body,string $name,?string $actionUrl=null,?string $logoPath=null,?int $workspaceId=null):string{return self::html($body,$name,$actionUrl,$logoPath,$workspaceId);}
 public static function lastError():string{return self::$lastError;}
 private static function deliver(string $to,string $subject,string $body,string $html,?string $attachment,?string $from,?string $name):bool{
  self::$lastError='';$token=trim((string)Env::get('BREVO_API_KEY',''));if($token===''){self::$lastError='BREVO_API_KEY není nastaven.';return false;}$from=$from?:Env::get('MAIL_FROM');if(!$from){self::$lastError='MAIL_FROM není nastaven.';return false;}$name=$name?:Env::get('MAIL_FROM_NAME','Byznio');$payload=['sender'=>['email'=>$from,'name'=>$name],'to'=>[['email'=>$to]],'subject'=>$subject,'textContent'=>$body,'htmlContent'=>$html];if(!empty($GLOBALS['_byznio_mail_reply_to'])){$payload['replyTo']=['email'=>$GLOBALS['_byznio_mail_reply_to']];unset($GLOBALS['_byznio_mail_reply_to']);}if($attachment){$file=@file_get_contents($attachment);if($file===false){self::$lastError='Přílohu se nepodařilo načíst.';return false;}$payload['attachment']=[['name'=>basename($attachment),'content'=>base64_encode($file)]];}
  $ch=curl_init('https://api.brevo.com/v3/smtp/email');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['accept: application/json','api-key: '.$token,'content-type: application/json'],CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>30,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2]);$response=curl_exec($ch);$errno=curl_errno($ch);$error=curl_error($ch);$http=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($response===false){self::$lastError='Brevo cURL chyba '.$errno.': '.$error;return false;}if($http<200||$http>=300){$decoded=json_decode($response,true);self::$lastError='Brevo HTTP '.$http.': '.($decoded['message']??$decoded['code']??$response);return false;}return true;
 }
 public static function send(string $to,string $subject,string $body,?string $attachment=null,?string $from=null,?string $name=null,?string $actionUrl=null,?string $logoPath=null,?int $workspaceId=null,?string $replyTo=null):bool{if($replyTo)$GLOBALS['_byznio_mail_reply_to']=$replyTo;return self::deliver($to,$subject,$body,self::html($body,$name?:Env::get('MAIL_FROM_NAME','Byznio'),$actionUrl,$logoPath,$workspaceId),$attachment,$from,$name);}
 public static function sendReport(string $to,string $subject,string $body,string $reportHtml,?string $from=null,?string $name=null,?string $actionUrl=null,?string $logoPath=null,?int $workspaceId=null,?string $replyTo=null):bool{$name=$name?:Env::get('MAIL_FROM_NAME','Byznio');if($replyTo)$GLOBALS['_byznio_mail_reply_to']=$replyTo;return self::deliver($to,$subject,$body,self::reportHtml($reportHtml,$name,$actionUrl,$logoPath,$workspaceId),null,$from,$name);}
}
