<?php
namespace App\Services;
use Dompdf\Dompdf;
use Dompdf\Options;
final class PdfService {
    private static function title(string $type): string { return ['invoice'=>'FAKTURA','offer'=>'NABÍDKA','order'=>'OBJEDNÁVKA','proforma'=>'ZÁLOHOVÁ FAKTURA','credit'=>'DOBROPIS'][$type] ?? 'DOKLAD'; }
    public static function invoice(array $doc,array $items,array $company,array $customer,?string $qrUrl=null): string {
        $esc=fn($x)=>htmlspecialchars((string)$x,ENT_QUOTES,'UTF-8'); $rows='';
        foreach($items as $i=>$it)$rows.='<tr><td>'.($i+1).'</td><td>'.$esc($it['name']).'</td><td>'.$esc($it['quantity']).' '.$esc($it['unit']).'</td><td>'.number_format((float)$it['unit_price'],2,',',' ').'</td><td>'.number_format((float)$it['line_total'],2,',',' ').'</td></tr>';
        $logoHtml=''; if(!empty($company['logo_path'])){ $logoFile=dirname(__DIR__,2).'/'.ltrim((string)$company['logo_path'],'/'); if(is_file($logoFile)){ $mime=(new \finfo(FILEINFO_MIME_TYPE))->file($logoFile); if(in_array($mime,['image/png','image/jpeg','image/svg+xml'],true))$logoHtml='<img src="data:'.$mime.';base64,'.base64_encode((string)file_get_contents($logoFile)).'" style="max-width:180px;max-height:58px;object-fit:contain;margin-bottom:8px" alt="Logo">'; }}
        $qrHtml=''; $iban=\App\Services\QrService::normalizeIban((string)($company['bank_account']??''));
        if(($doc['doc_type']??'')==='invoice'){
            $qrUrlSafe=$qrUrl?'<a href="'.$esc($qrUrl).'">':''; $qrEnd=$qrUrl?'</a>':'';
            if($iban){
                try{
                    $spayd=\App\Services\QrService::spayd((string)$company['bank_account'],(float)$doc['total_with_vat'],(string)($doc['variable_symbol']??''));
                    $qr=\App\Services\QrService::png((string)$spayd,240,10);
                    $qrHtml='<div class="payment"><div class="payment-info"><div class="payment-title">Úhrada faktury</div><div><b>Bankovní účet</b><br>'. $esc((string)$company['bank_account']) .'</div><div style="margin-top:8px"><b>Variabilní symbol</b><br>'. $esc((string)($doc['variable_symbol']??'')) .'</div><div style="margin-top:8px"><b>Částka k úhradě</b><br><span class="payment-amount">'.number_format((float)$doc['total_with_vat'],2,',',' ').' Kč</span></div></div><div class="qrbox">'.$qrUrlSafe.'<img src="'.$qr['data_uri'].'" style="width:150px;height:150px" alt="QR platba">'.$qrEnd.'<div class="qrlabel">QR PLATBA</div></div></div>';
                }catch(\Throwable $e){
                    $qrHtml='<div class="payment payment-warning"><div><div class="payment-title">Úhrada faktury</div><div>QR platbu se nepodařilo vygenerovat. Zkontrolujte nastavení bankovního účtu v Nastavení firmy.</div></div></div>';
                }
            } else {
                $qrHtml='<div class="payment payment-warning"><div><div class="payment-title">Úhrada faktury</div><div>Pro QR platbu nastavte v Nastavení firmy bankovní účet ve formátu <b>123456789/0800</b> nebo platný IBAN.</div></div></div>';
            }
        }
        $html='<!doctype html><html lang="cs"><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:11px;margin:34px 38px}.top{width:100%;border-bottom:2px solid #182234;padding-bottom:18px}.top td{vertical-align:top}.brand{width:58%}.brand h1{font-size:29px;letter-spacing:-.5px;margin:4px 0 2px}.docno{font-size:12px;color:#667085;font-weight:700}.company{text-align:right;line-height:1.55;color:#344054}.muted{color:#667085}.grid{width:100%;margin:24px 0 18px}.grid td{width:50%;vertical-align:top}.box-title{font-size:10px;text-transform:uppercase;letter-spacing:.7px;color:#667085;font-weight:800;margin-bottom:5px}.box{line-height:1.55}.meta{text-align:right}.meta strong{color:#172033}.items{width:100%;border-collapse:collapse;margin-top:18px}.items th{background:#121b2d;color:#fff;text-align:left;padding:9px 8px;font-size:10px}.items td{border-bottom:1px solid #e5e7eb;padding:9px 8px}.items th:nth-child(1),.items td:nth-child(1){width:28px}.items th:nth-child(3),.items td:nth-child(3){width:85px}.items th:nth-child(4),.items td:nth-child(4),.items th:nth-child(5),.items td:nth-child(5){text-align:right}.summary{width:100%;margin-top:18px}.summary td{vertical-align:top}.total{width:250px;margin-left:auto}.line{padding:5px 0;text-align:right}.grand{border-top:2px solid #182234;margin-top:4px;padding-top:9px;font-size:17px;font-weight:800}.payment{width:100%;margin-top:20px;border:1px solid #dbe2ea;border-radius:12px;background:#f7f9fc;padding:14px;box-sizing:border-box}.payment td{vertical-align:middle}.payment-info{width:68%;line-height:1.45}.payment-title{font-size:14px;font-weight:800;margin-bottom:7px}.payment-amount{font-size:15px;font-weight:800}.qrbox{width:32%;text-align:center}.qrbox img{display:block;margin:0 auto}.qrlabel{font-size:9px;font-weight:800;letter-spacing:1px;margin-top:4px}.payment-warning{color:#475467}.footer{margin-top:26px;padding-top:10px;border-top:1px solid #e5e7eb;font-size:9px;color:#98a2b3;text-align:center}.logo{max-width:170px;max-height:52px;object-fit:contain;margin-bottom:4px}
</style><table class="top"><tr><td class="brand">'.$logoHtml.'<div class="muted">BYZNIO</div><h1>'.$esc(self::title($doc['doc_type']??'invoice')).'</h1><div class="docno">'.$esc($doc['doc_number']).'</div></td><td class="company"><b>'.$esc($company['name']??'').'</b><br>'.$esc($company['street']??'').'<br>'.$esc(($company['zip']??'').' '.($company['city']??'')).'<br>IČO '.$esc($company['ico']??'').($company['dic']??''?'<br>DIČ '.$esc($company['dic']):'').'</td></tr></table><table class="grid"><tr><td><div class="box-title">Odběratel</div><div class="box"><b>'.$esc($customer['company_name']??trim(($customer['first_name']??'').' '.($customer['last_name']??''))).'</b><br>'.$esc($customer['street']??'').'<br>'.$esc(($customer['zip']??'').' '.($customer['city']??'')).'</div></td><td class="meta"><div class="box-title">Doklad</div><div class="box"><b>Vystaveno:</b> '.$esc($doc['issue_date']??'').' <br><b>Splatnost:</b> '.$esc($doc['due_date']??'').' <br><b>Variabilní symbol:</b> '.$esc($doc['variable_symbol']??'').'</div></td></tr></table><table class="items"><thead><tr><th>#</th><th>Položka</th><th>Množství</th><th>Jedn. cena</th><th>Celkem</th></tr></thead><tbody>'.$rows.'</tbody></table><table class="summary"><tr><td></td><td><div class="total"><div class="line">Bez DPH &nbsp; <b>'.number_format((float)$doc['total_without_vat'],2,',',' ').' Kč</b></div><div class="line">DPH &nbsp; <b>'.number_format((float)$doc['total_vat'],2,',',' ').' Kč</b></div><div class="line grand">K úhradě &nbsp; '.number_format((float)$doc['total_with_vat'],2,',',' ').' Kč</div></div></td></tr></table>'.$qrHtml.'<div class="footer">Dokument vytvořen systémem Byznio.</div></html>';
        $o=new Options();$o->set('defaultFont','DejaVu Sans');$o->set('isRemoteEnabled',false);$d=new Dompdf($o);$d->loadHtml($html,'UTF-8');$d->setPaper('A4');$d->render();return $d->output();
    }
}
