<?php
namespace App\Services;
use PDO;
final class TaxService {
 public static function estimate(array $d):array{$income=(float)$d['income'];$expenses=(float)$d['expenses'];$method=$d['income_tax_method']??'actual';$base=$method==='lump'?$income*(1-(float)($d['expense_lump_rate']??0.6)):max(0,$income-$expenses);$vat=(float)($d['vat']??0);$social=$base*(float)($d['social_rate']??0);$health=$base*(float)($d['health_rate']??0);$tax=max(0,$base*0.15-(float)($d['tax_credit']??0));if(!empty($d['flat_regime'])){$tax=(float)($d['flat_monthly_tax']??0)*12;$social=(float)($d['flat_social_monthly']??0)*12;$health=(float)($d['flat_health_monthly']??0)*12;}return ['year'=>(int)($d['year']??date('Y')),'income'=>$income,'expenses'=>$expenses,'base'=>$base,'vat'=>$vat,'social'=>$social,'health'=>$health,'income_tax'=>$tax,'total'=>$tax+$social+$health,'note'=>'Orientační výpočet podkladů. Nejde o daňové přiznání.'];}
 public static function calculate(PDO $db,int $wid,int $year,array $profile=[]):array{
   $from=$year.'-01-01';$to=$year.'-12-31';$vatPayer=!empty($profile['vat_payer']);
   $dateExpr="CASE WHEN d.doc_type='credit' THEN d.issue_date ELSE d.issue_date END";
   $q=$db->prepare("SELECT d.*,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.document_id=d.id AND p.workspace_id=d.workspace_id AND p.paid_at BETWEEN ? AND ?),0) paid_year FROM documents d WHERE d.workspace_id=? AND d.issue_date BETWEEN ? AND ? AND d.status<>'cancelled' AND d.doc_type IN ('invoice','credit')");$q->execute([$from,$to,$wid,$from,$to]);
   $income=0;$credits=0;$vatOut=0;$docs=[];$cashEvidence=($profile['income_tax_method']??'actual')==='cash';
   foreach($q as $d){$gross=(float)$d['total_with_vat'];$base=$vatPayer?(float)$d['total_without_vat']:$gross;$vat=(float)$d['total_vat'];$isCredit=$d['doc_type']==='credit';$value=$cashEvidence?(float)$d['paid_year']:$gross;if($cashEvidence&&$gross>0)$ratio=$value/$gross;else $ratio=1;$adjBase=$base*$ratio;$adjVat=$vat*$ratio;if($isCredit){$income-=$adjBase;$credits+=$adjBase;$vatOut-=$adjVat;}else{$income+=$adjBase;$vatOut+=$adjVat;}$docs[]=['doc_number'=>$d['doc_number'],'type'=>$d['doc_type'],'date'=>$d['issue_date'],'paid_year'=>(float)$d['paid_year'],'amount'=>$adjBase];}
   $q=$db->prepare('SELECT COALESCE(SUM(amount),0) FROM expenses WHERE workspace_id=? AND expense_date BETWEEN ? AND ?');$q->execute([$wid,$from,$to]);$expenses=(float)$q->fetchColumn();$q=$db->prepare('SELECT COALESCE(SUM(vat_amount),0) FROM expenses WHERE workspace_id=? AND expense_date BETWEEN ? AND ?');$q->execute([$wid,$from,$to]);$vatIn=(float)$q->fetchColumn();
   $estimate=self::estimate(['income'=>$income,'expenses'=>$expenses,'vat'=>max(0,$vatOut-$vatIn),'social_rate'=>$profile['social_rate']??0,'health_rate'=>$profile['health_rate']??0,'income_tax_method'=>$profile['income_tax_method']??'actual','flat_regime'=>$profile['flat_regime']??0,'flat_monthly_tax'=>$profile['flat_monthly_tax']??0,'flat_social_monthly'=>$profile['flat_social_monthly']??0,'flat_health_monthly'=>$profile['flat_health_monthly']??0,'tax_credit'=>$profile['tax_credit']??0,'expense_lump_rate'=>$profile['expense_lump_rate']??0.6,'year'=>$year]);
   $estimate['vat_output']=$vatOut;$estimate['vat_input']=$vatIn;$estimate['vat_to_pay']=max(0,$vatOut-$vatIn);$estimate['credits']=$credits;$estimate['documents']=$docs;return $estimate;
 }
}
