<style>
.ai-shell{max-width:920px;margin:0 auto}.ai-hero{display:flex;gap:18px;align-items:flex-start;margin-bottom:18px}.ai-avatar{width:64px;height:64px;flex:0 0 64px;border:1px solid #cfe0f7;border-radius:20px;background:linear-gradient(145deg,#edf6ff,#f7f1ff);display:grid;place-items:center;position:relative;overflow:hidden}.ai-avatar svg{width:48px;height:48px}.ai-avatar.idle{animation:ai-breathe 3.6s ease-in-out infinite}.ai-avatar.thinking .dot{animation:ai-dot 1s infinite}.ai-avatar.thinking .dot:nth-child(2){animation-delay:.16s}.ai-avatar.thinking .dot:nth-child(3){animation-delay:.32s}.ai-avatar.alert{animation:ai-alert 2.4s ease-in-out infinite}.ai-avatar .dot{opacity:.35}.ai-bubble{background:#fff;border:1px solid var(--line);border-radius:18px 18px 18px 6px;padding:16px 18px;box-shadow:var(--shadow);line-height:1.6;flex:1}.ai-bubble strong{display:block;margin-bottom:5px}.ai-brief{margin:0 0 18px;padding-left:82px}.ai-brief li{margin:7px 0;color:#45546b}.ai-chat{display:grid;gap:14px}.ai-msg{display:flex;gap:10px;align-items:flex-end}.ai-msg.user{justify-content:flex-end}.ai-msg.user .ai-msg-bubble{background:#edf4ff;border-color:#d3e4ff;border-radius:18px 18px 6px 18px}.ai-msg-bubble{max-width:min(78%,700px);padding:13px 15px;border:1px solid var(--line);border-radius:18px 18px 18px 6px;background:#fff;line-height:1.55;white-space:pre-wrap}.ai-mini-avatar{width:30px;height:30px;flex:0 0 30px;border-radius:10px;background:#edf6ff;display:grid;place-items:center}.ai-mini-avatar svg{width:24px;height:24px}.ai-chips{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 18px}.ai-chip{border:1px solid #d8e3f1;background:#fff;border-radius:999px;padding:9px 12px;cursor:pointer;font-weight:700;color:#33465f}.ai-chip:hover{border-color:#9bbce8;background:#f8fbff}.ai-composer{position:sticky;bottom:12px;margin-top:18px;background:rgba(255,255,255,.94);backdrop-filter:blur(10px);border:1px solid var(--line);border-radius:18px;padding:12px;box-shadow:0 12px 35px rgba(16,33,63,.10)}.ai-composer form{display:flex;gap:10px}.ai-composer textarea{flex:1;min-height:48px;max-height:140px;resize:vertical;border:1px solid #d6deea;border-radius:13px;padding:12px 13px;font:inherit;outline:none}.ai-composer textarea:focus{border-color:#7db0f4;box-shadow:0 0 0 4px rgba(22,119,238,.1)}.ai-action{border:1px solid #d9c7ff;background:#f8f4ff;border-radius:16px;padding:16px;margin-top:4px}.ai-action h3{margin:0 0 8px}.ai-action pre{white-space:pre-wrap;word-break:break-word;background:#fff;border:1px solid #e4dafc;padding:11px;border-radius:10px;font-size:12px}.ai-actions{display:flex;gap:9px;flex-wrap:wrap}.ai-status{font-size:13px;color:var(--muted);min-height:20px;margin-top:7px}
@keyframes ai-breathe{0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-2px) scale(1.035)}}@keyframes ai-dot{0%,70%,100%{opacity:.25;transform:translateY(0)}35%{opacity:1;transform:translateY(-3px)}}@keyframes ai-alert{0%,100%{box-shadow:0 0 0 rgba(245,158,11,0);filter:hue-rotate(0deg)}50%{box-shadow:0 0 0 6px rgba(245,158,11,.12);filter:hue-rotate(22deg)}}
@media(max-width:600px){.ai-hero{gap:12px}.ai-avatar{width:54px;height:54px;flex-basis:54px;border-radius:17px}.ai-avatar svg{width:42px;height:42px}.ai-brief{padding-left:66px}.ai-msg-bubble{max-width:86%}.ai-composer{bottom:6px}.ai-composer form{align-items:stretch}.ai-composer .btn{width:auto}.ai-chip{width:auto}}
</style>
<div class="ai-shell">
<div class="page-head"><div><h1>AI asistent</h1><div class="sub">Nia zná kontext vaší firmy a pomůže vám s každodenní prací.</div></div></div>
<div class="ai-hero"><div class="ai-avatar <?=!empty($attention)?'alert':'idle'?>" data-avatar><svg viewBox="0 0 76 76" fill="none" aria-hidden="true"><circle cx="38" cy="24" r="14" fill="#FFD8C2"/><path d="M24 23c1-12 25-18 29-1-5-4-10-5-16-3-3 1-7 3-13 4Z" fill="#20395F"/><circle cx="33" cy="25" r="1.7" fill="#17345A"/><circle cx="43" cy="25" r="1.7" fill="#17345A"/><path class="dot" d="M34 31c2.2 2.1 5.8 2.1 8 0" stroke="#B85B65" stroke-width="1.8" stroke-linecap="round"/><path d="M25 42c3-5 23-5 26 0l4 23H21l4-23Z" fill="#5B46E8"/><path d="M25 47 14 57M51 47l11 10" stroke="#FFD8C2" stroke-width="7" stroke-linecap="round"/></svg></div><div class="ai-bubble"><strong>Ahoj, já jsem Nia.</strong><?php foreach(($briefing??[]) as $line): ?><div><?=View::e($line)?></div><?php endforeach; ?></div></div>
<ul class="ai-brief"><?php foreach(($briefing??[]) as $line): ?><li><?=View::e($line)?></li><?php endforeach; ?></ul>
<div class="ai-chat" id="aiChat"></div>
<div class="ai-chips" id="aiChips"><?php foreach(($chips??[]) as $chip): ?><button type="button" class="ai-chip" data-prompt="<?=View::e($chip)?>"><?=View::e($chip)?></button><?php endforeach; ?></div>
<div id="aiPending"></div>
<div class="ai-composer"><form id="aiForm"><input type="hidden" name="_csrf" value="<?=View::e($csrf??App\Core\Auth::csrf())?>"><textarea id="aiPrompt" name="prompt" placeholder="Napište Nii, co potřebujete…" rows="1"></textarea><button class="btn accent" type="submit">Odeslat</button></form><div class="ai-status" id="aiStatus" aria-live="polite"></div></div>
</div>
<script>
(function(){
const root=document.querySelector('.ai-shell');if(!root)return;const form=document.getElementById('aiForm'),prompt=document.getElementById('aiPrompt'),chat=document.getElementById('aiChat'),status=document.getElementById('aiStatus'),pendingBox=document.getElementById('aiPending'),avatar=document.querySelector('[data-avatar]');
const svg='<svg viewBox="0 0 76 76" fill="none" aria-hidden="true"><circle cx="38" cy="24" r="14" fill="#FFD8C2"/><path d="M24 23c1-12 25-18 29-1-5-4-10-5-16-3-3 1-7 3-13 4Z" fill="#20395F"/><circle cx="33" cy="25" r="1.7" fill="#17345A"/><circle cx="43" cy="25" r="1.7" fill="#17345A"/><path class="dot" d="M34 31c2.2 2.1 5.8 2.1 8 0" stroke="#B85B65" stroke-width="1.8" stroke-linecap="round"/><path d="M25 42c3-5 23-5 26 0l4 23H21l4-23Z" fill="#5B46E8"/><path d="M25 47 14 57M51 47l11 10" stroke="#FFD8C2" stroke-width="7" stroke-linecap="round"/></svg>';
avatar.innerHTML=svg;
function add(role,text){const row=document.createElement('div');row.className='ai-msg '+role;if(role==='assistant'){const mini=document.createElement('div');mini.className='ai-mini-avatar';mini.innerHTML=svg;row.appendChild(mini)}const b=document.createElement('div');b.className='ai-msg-bubble';b.textContent=text;row.appendChild(b);chat.appendChild(row);row.scrollIntoView({behavior:'smooth',block:'nearest'});}
function renderPending(p){pendingBox.innerHTML='';if(!p)return;const card=document.createElement('div');card.className='ai-action';const title=document.createElement('h3');title.textContent='Nia připravila návrh akce';card.appendChild(title);const pre=document.createElement('pre');pre.textContent=JSON.stringify(p.payload,null,2);card.appendChild(pre);const actions=document.createElement('div');actions.className='ai-actions';const yes=document.createElement('button');yes.className='btn primary';yes.type='button';yes.textContent='Potvrdit';const no=document.createElement('button');no.className='btn';no.type='button';no.textContent='Zrušit';actions.append(yes,no);card.appendChild(actions);pendingBox.appendChild(card);yes.onclick=async()=>{yes.disabled=true;status.textContent='Nia provádí potvrzenou akci…';const fd=new FormData(form);const r=await fetch('/ai/confirm',{method:'POST',body:fd,headers:{'X-Requested-With':'fetch'}});const j=await r.json();if(j.ok){add('assistant',j.message||'Hotovo.');pendingBox.innerHTML='';status.textContent='';}else{yes.disabled=false;status.textContent=j.error||'Akci se nepodařilo provést.';}};no.onclick=()=>{fetch('/ai/cancel',{method:'POST',body:new URLSearchParams({_csrf:form._csrf.value}),headers:{'X-Requested-With':'fetch'}}).catch(()=>{});pendingBox.innerHTML='';status.textContent='Návrh byl zrušen.';};}
async function ask(text){text=text.trim();if(!text)return;add('user',text);prompt.value='';status.textContent='Nia přemýšlí…';avatar.classList.remove('idle','alert');avatar.classList.add('thinking');const fd=new FormData(form);fd.set('prompt',text);try{const r=await fetch('/ai/ask',{method:'POST',body:fd,headers:{'X-Requested-With':'fetch'}});const j=await r.json();if(!j.ok)throw new Error(j.error||'Chyba');add('assistant',j.answer||'');renderPending(j.pending);status.textContent='';}catch(e){add('assistant','Teď se mi nepodařilo odpovědět. Zkuste to prosím znovu.');status.textContent='';}finally{avatar.classList.remove('thinking');avatar.classList.add('idle');}}
form.addEventListener('submit',e=>{e.preventDefault();ask(prompt.value)});document.querySelectorAll('.ai-chip').forEach(b=>b.addEventListener('click',()=>ask(b.dataset.prompt)));prompt.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit();}});
})();
</script>