<?php $edit=!empty($customer['id']); $deliverySame=empty($customer['delivery_street']) && empty($customer['delivery_city']) && empty($customer['delivery_zip']); ?>
<h1 class="h"><?=$edit?'Upravit zákazníka':'Nový zákazník'?></h1>
<div class="sub">Firemní i soukromé kontakty. IČO lze doplnit přes ARES.</div>
<form class="form" method="post" action="<?=$edit?'/customers/'.$customer['id'].'/update':'/customers/save'?>">
<input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>">
<div class="row"><div class="field"><label>Typ</label><select name="type"><option value="company" <?=($customer['type']??'company')==='company'?'selected':''?>>Firma</option><option value="person" <?=($customer['type']??'')==='person'?'selected':''?>>Osoba</option></select></div><div class="field"><label>IČO</label><div style="display:flex;gap:8px"><input name="ico" id="customerAresIco" value="<?=\App\Core\View::e($customer['ico']??'')?>"><button type="button" class="btn" id="customerAresBtn">Načíst z ARES</button></div><small id="customerAresStatus" style="display:block;color:#718098;margin-top:5px">Zadejte IČO a Byznio doplní firemní údaje.</small></div></div>
<div class="field"><label>Název firmy</label><input name="company_name" value="<?=\App\Core\View::e($customer['company_name']??'')?>"></div>
<div class="row"><div class="field"><label>Jméno</label><input name="first_name" value="<?=\App\Core\View::e($customer['first_name']??'')?>"></div><div class="field"><label>Příjmení</label><input name="last_name" value="<?=\App\Core\View::e($customer['last_name']??'')?>"></div></div>
<div class="row"><div class="field"><label>DIČ</label><input name="dic" value="<?=\App\Core\View::e($customer['dic']??'')?>"></div><div class="field"><label>E-mail</label><input type="email" name="email" value="<?=\App\Core\View::e($customer['email']??'')?>"></div></div>
<div class="row"><div class="field"><label>Telefon</label><input name="phone" value="<?=\App\Core\View::e($customer['phone']??'')?>"></div><div class="field"><label>Web</label><input name="web" value="<?=\App\Core\View::e($customer['web']??'')?>"></div></div>
<div class="card customer-address-card"><h3>Fakturační adresa</h3><p class="sub">Adresa zákazníka používaná na fakturách a dalších dokladech.</p><div class="row"><div class="field"><label>Ulice</label><input name="street" value="<?=\App\Core\View::e($customer['street']??'')?>"></div><div class="field"><label>Město</label><input name="city" value="<?=\App\Core\View::e($customer['city']??'')?>"></div></div><div class="field"><label>PSČ</label><input name="zip" value="<?=\App\Core\View::e($customer['zip']??'')?>" inputmode="numeric" autocomplete="postal-code"></div></div>
<div class="card customer-address-card"><h3>Dodací adresa</h3><p class="sub">Pokud je stejná jako fakturační, nic dalšího nastavovat nemusíte.</p><label class="switch customer-delivery-toggle"><input type="checkbox" id="deliveryDifferent" name="delivery_different" value="1" <?=!$deliverySame?'checked':''?>><span class="track"></span><span>Dodací adresa je jiná než fakturační</span></label><div id="deliveryFields" class="delivery-fields" style="display:<?=!$deliverySame?'block':'none'?>"><div class="row"><div class="field"><label>Ulice</label><input name="delivery_street" value="<?=\App\Core\View::e($customer['delivery_street']??'')?>"></div><div class="field"><label>Město</label><input name="delivery_city" value="<?=\App\Core\View::e($customer['delivery_city']??'')?>"></div></div><div class="field"><label>PSČ</label><input name="delivery_zip" value="<?=\App\Core\View::e($customer['delivery_zip']??'')?>" inputmode="numeric" autocomplete="postal-code"></div></div></div>
<div class="field"><label>Poznámka</label><textarea name="note"><?=\App\Core\View::e($customer['note']??'')?></textarea></div>
<?php if(!$edit):?><label><input type="checkbox" name="ares" value="1"> při uložení doplnit údaje z ARES</label><?php endif;?>
<button class="btn primary"><?=$edit?'Uložit změny':'Uložit zákazníka'?></button>
</form>
<script>
(function(){const c=document.getElementById('deliveryDifferent'),f=document.getElementById('deliveryFields');if(!c||!f)return;function sync(){f.style.display=c.checked?'block':'none';if(!c.checked)f.querySelectorAll('input').forEach(i=>i.value='')}c.addEventListener('change',sync)})();
const ab=document.getElementById('customerAresBtn'),ai=document.getElementById('customerAresIco'),as=document.getElementById('customerAresStatus');ab?.addEventListener('click',async()=>{const ico=(ai.value||'').replace(/\D/g,'');ai.value=ico;if(ico.length!==8){as.textContent='IČO musí mít 8 číslic.';as.style.color='#b42318';return}ab.disabled=true;ab.textContent='Načítám…';try{const fd=new FormData();fd.append('_csrf',document.querySelector('input[name="_csrf"]')?.value||'');fd.append('ico',ico);const r=await fetch('/customers/ares',{method:'POST',body:fd});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'ARES se nepodařilo načíst.');const d=j.data||{};const set=(name,v)=>{const el=document.querySelector('[name="'+name+'"]');if(el&&v!==undefined)el.value=v||''};set('company_name',d.company_name);set('dic',d.dic);set('street',d.street);set('city',d.city);set('zip',d.zip);as.textContent='Údaje z ARES načteny.';as.style.color='#16824a'}catch(e){as.textContent=e.message;as.style.color='#b42318'}finally{ab.disabled=false;ab.textContent='Načíst z ARES'}});
</script>
