<?php
namespace App\Controllers;
use App\Core\{Auth,Database,Response};
use App\Services\AiService;
use App\Services\DocumentService;
final class ApiController {
    private static function auth():void{
        $h=$_SERVER['HTTP_AUTHORIZATION']??'';preg_match('/Bearer\s+(.+)/i',$h,$m);$key=$m[1]??'';
        $s=Database::pdo()->prepare('SELECT u.* FROM api_keys k JOIN users u ON u.id=k.user_id WHERE k.key_hash=? AND u.active=1');$s->execute([hash('sha256',$key)]);$u=$s->fetch();
        if(!$u)Response::json(['error'=>'unauthorized'],401);Database::pdo()->prepare('UPDATE api_keys SET last_used_at=CURRENT_TIMESTAMP WHERE key_hash=?')->execute([hash('sha256',$key)]);Auth::login($u);
    }
    private static function p():\PDO{return Database::pdo();}
    private static function gateApi(): void { $s=self::p()->prepare('SELECT status,trial_ends_at,free_until FROM subscriptions WHERE workspace_id=?');$s->execute([Auth::workspaceId()]);$sub=$s->fetch()?:[];$ok=in_array((string)($sub['status']??''),['trial','active','free'],true)&&((empty($sub['trial_ends_at'])||$sub['trial_ends_at']>=date('Y-m-d H:i:s'))&&(empty($sub['free_until'])||$sub['free_until']>=date('Y-m-d H:i:s')));if(!$ok)Response::json(['error'=>'subscription_required','message'=>'Předplatné není aktivní.'],402); }
    public static function customers():never{self::auth();self::gateApi();$s=self::p()->prepare('SELECT * FROM customers WHERE workspace_id=? AND active=1 ORDER BY id DESC');$s->execute([Auth::workspaceId()]);Response::json($s->fetchAll());}
    public static function customerCreate():never{self::auth();self::gateApi();$d=json_decode(file_get_contents('php://input'),true)?:[];$s=self::p()->prepare('INSERT INTO customers(workspace_id,type,company_name,ico,dic,email,phone,street,city,zip) VALUES(?,?,?,?,?,?,?,?,?,?)');$s->execute([Auth::workspaceId(),$d['type']??'company',$d['company_name']??null,$d['ico']??null,$d['dic']??null,$d['email']??null,$d['phone']??null,$d['street']??null,$d['city']??null,$d['zip']??null]);Response::json(['id'=>(int)self::p()->lastInsertId()],201);}
    public static function documents():never{self::auth();self::gateApi();$s=self::p()->prepare('SELECT * FROM documents WHERE workspace_id=? ORDER BY id DESC');$s->execute([Auth::workspaceId()]);Response::json($s->fetchAll());}
    public static function documentCreate():never{self::auth();self::gateApi();$d=json_decode(file_get_contents('php://input'),true)?:[];$items=$d['items']??[];$sub=$vat=0;foreach($items as &$it){$line=round((float)($it['quantity']??1)*(float)($it['unit_price']??0),2);$it['line_total']=$line;$sub+=$line;$vat+=round($line*(float)($it['vat_rate']??21)/100,2);} $n=DocumentService::nextNumber(self::p(),Auth::workspaceId(),(string)($d['doc_type']??'invoice'));$st=self::p()->prepare('INSERT INTO documents(workspace_id,doc_type,doc_number,variable_symbol,customer_id,status,payment_status,issue_date,due_date,total_without_vat,total_vat,total_with_vat,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute([Auth::workspaceId(),$d['doc_type']??'invoice',$n,preg_replace('/\D/','',$n),(int)$d['customer_id'],'issued','unpaid',$d['issue_date']??date('Y-m-d'),$d['due_date']??date('Y-m-d',strtotime('+14 days')),$sub,$vat,$sub+$vat,Auth::id()]);$id=(int)self::p()->lastInsertId();$is=self::p()->prepare('INSERT INTO document_items(document_id,name,quantity,unit,unit_price,vat_rate,line_total) VALUES(?,?,?,?,?,?,?)');foreach($items as $it)$is->execute([$id,$it['name'],(float)($it['quantity']??1),$it['unit']??'ks',(float)$it['unit_price'],(float)($it['vat_rate']??21),(float)$it['line_total']]);Response::json(['id'=>$id,'doc_number'=>$n],201);}
    public static function jobs():never{self::auth();self::gateApi();$s=self::p()->prepare('SELECT * FROM jobs WHERE workspace_id=? ORDER BY id DESC');$s->execute([Auth::workspaceId()]);Response::json($s->fetchAll());}
    public static function transactions():never{self::auth();self::gateApi();$s=self::p()->prepare('SELECT * FROM bank_transactions WHERE workspace_id=? ORDER BY booked_at DESC');$s->execute([Auth::workspaceId()]);Response::json($s->fetchAll());}
    public static function products():never{self::auth();self::gateApi();$s=self::p()->prepare('SELECT * FROM products WHERE workspace_id=? ORDER BY name');$s->execute([Auth::workspaceId()]);Response::json($s->fetchAll());}
    public static function apiKeyCreate():never{self::auth();self::gateApi();$raw=bin2hex(random_bytes(24));$hash=hash('sha256',$raw);self::p()->prepare('INSERT INTO api_keys(user_id,name,key_hash) VALUES(?,?,?)')->execute([Auth::id(),$_POST['name']??'API key',$hash]);Response::json(['key'=>$raw],201);}
    public static function aiAsk():never{self::auth();self::gateApi();$d=json_decode(file_get_contents('php://input'),true)?:[];Response::json(['answer'=>AiService::ask((string)($d['prompt']??''),['workspace_id'=>Auth::workspaceId()])]);}
    public static function customerUpdate(int $id):never{self::auth();self::gateApi();$d=json_decode(file_get_contents('php://input'),true)?:[];$p=self::p();$s=$p->prepare('UPDATE customers SET company_name=?,email=?,phone=?,street=?,city=?,zip=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?');$s->execute([$d['company_name']??null,$d['email']??null,$d['phone']??null,$d['street']??null,$d['city']??null,$d['zip']??null,$id,Auth::workspaceId()]);Response::json(['updated'=>$s->rowCount()>0]);}
    public static function customerDelete(int $id):never{self::auth();self::gateApi();$s=self::p()->prepare('UPDATE customers SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?');$s->execute([$id,Auth::workspaceId()]);Response::json(['deleted'=>$s->rowCount()>0]);}
    public static function documentUpdate(int $id):never{self::auth();self::gateApi();$d=json_decode(file_get_contents('php://input'),true)?:[];$p=self::p();$s=$p->prepare('UPDATE documents SET due_date=?,notes=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?');$s->execute([$d['due_date']??null,$d['notes']??null,$d['status']??'issued',$id,Auth::workspaceId()]);Response::json(['updated'=>$s->rowCount()>0]);}
    public static function documentDelete(int $id):never{self::auth();self::gateApi();$p=self::p();$s=$p->prepare('SELECT id FROM documents WHERE id=? AND workspace_id=?');$s->execute([$id,Auth::workspaceId()]);if(!$s->fetchColumn())Response::json(['error'=>'not_found'],404);$p->prepare("UPDATE documents SET status='cancelled',payment_status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?")->execute([$id,Auth::workspaceId()]);Response::json(['cancelled'=>true]);}

}
