<div class="page-head"><div><h1>Automatizace</h1><div class="sub">Automatizace jsou konkrétní pravidla „KDYŽ → PAK“. Byznio je provádí při pravidelné kontrole systému.</div></div></div>
<div class="card automation-intro"><h3>Co to znamená v praxi?</h3><div class="automation-examples">
<div><b>💰 Přijde platba</b><p>Byznio vezme novou příchozí platbu a zkusí ji najít mezi nezaplacenými fakturami. Použije hlavně <strong>variabilní symbol + částku</strong>, případně číslo faktury v poznámce. Jednoznačnou shodu může označit jako uhrazenou; nejasnou nechá ke kontrole.</p></div>
<div><b>📅 Blíží se splatnost</b><p>Byznio najde faktury, kterým se blíží nebo už uplynula splatnost, a připraví e-mailovou upomínku. Odeslání probíhá přes e-mailovou frontu.</p></div>
<div><b>📦 Sklad klesne pod minimum</b><p>Byznio vytvoří úkol „Doplnit sklad: …“, aby na nízkou zásobu upozornil.</p></div>
<div><b>📈 Zakázka překročí rozpočet</b><p>Byznio vytvoří urgentní úkol k zakázce, jejíž skutečné náklady překročily rozpočet.</p></div>
</div><p class="sub" style="margin-bottom:0">Důležité: bankovní párování už probíhá automaticky při importu/synchronizaci. Pravidlo „Přijde platba → spárovat“ slouží jako opakovaná kontrola nevyřešených příchozích plateb.</p></div>
<div class="card"><h3>Nové pravidlo</h3><form class="row" method="post" action="/automation/save"><input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>"><div class="field"><label>Název pravidla</label><input name="name" placeholder="Např. Kontrolovat nové bankovní platby" required></div><div class="field"><label>KDYŽ nastane</label><select name="trigger_type"><option value="payment_received">Přijde platba z banky</option><option value="invoice_due">Blíží se / uplynula splatnost faktury</option><option value="stock_low">Sklad klesne pod minimum</option><option value="job_over_budget">Zakázka překročí rozpočet</option><option value="task_due">Blíží se termín úkolu</option></select></div><div class="field"><label>PAK udělej</label><select name="action_type"><option value="match_payment">Zkusit spárovat platbu s fakturou</option><option value="send_reminder">Připravit upomínku</option><option value="notify">Upozornit uživatele</option><option value="create_task">Vytvořit úkol</option></select></div><div class="field"><label>Parametr / počet dní</label><input name="days" type="number" min="0" value="0"><small>Např. 3 = kontrola 3 dny před/po termínu podle konkrétní automatizace.</small></div><div style="grid-column:1/-1"><button class="btn primary">Přidat automatizaci</button></div></form></div>
<div style="height:16px"></div><?php if(!$rules): ?><div class="card"><p class="sub">Zatím nemáte žádnou automatizaci.</p></div><?php endif; ?><?php foreach($rules as $r):?><div class="card automation-rule" style="margin-bottom:10px"><div><b><?=\App\Core\View::e($r['name'])?></b><div class="sub"><?=\App\Core\View::e(match((string)$r['trigger_type']){'payment_received'=>'Při přijetí platby z banky','invoice_due'=>'Při splatnosti faktury','stock_low'=>'Při nízké zásobě','job_over_budget'=>'Při překročení rozpočtu zakázky','task_due'=>'Při blížícím se termínu úkolu',default=>$r['trigger_type']})?> → <?=\App\Core\View::e(match((string)$r['action_type']){'match_payment'=>'zkusit spárovat s fakturou','send_reminder'=>'připravit upomínku','notify'=>'upozornit uživatele','create_task'=>'vytvořit úkol',default=>$r['action_type']})?></div></div><span class="badge <?=!empty($r['active'])?'ok':'warn'?>"><?=!empty($r['active'])?'Aktivní':'Pozastavená'?></span></div><?php endforeach;?>
<?php if(!empty($runs)): ?><div class="card"><h3>Poslední běhy</h3><table class="table"><tr><th>Čas</th><th>Pravidlo</th><th>Stav</th><th>Výsledek</th></tr><?php foreach($runs as $run): ?><tr><td><?=\App\Core\View::e($run['created_at'])?></td><td><?=\App\Core\View::e($run['name']??'Automatizace')?></td><td><span class="badge <?=$run['status']==='ok'?'ok':'warn'?>"><?=\App\Core\View::e($run['status'])?></span></td><td><?=\App\Core\View::e($run['message'])?></td></tr><?php endforeach; ?></table></div><?php endif; ?>
<style>.automation-examples{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.automation-examples>div{padding:14px;border:1px solid #e5eaf2;border-radius:14px;background:#fbfcff}.automation-examples p{margin:7px 0 0;color:#64748b;font-size:13px;line-height:1.5}@media(max-width:700px){.automation-examples{grid-template-columns:1fr}}</style>