<div class="page-head"><div><h1>Přidat další firmu</h1><div class="sub">Spravujte více firem pod jedním přihlášením. Každá firma má vlastní data a nastavení.</div></div></div>
<form class="form" method="post"><input type="hidden" name="_csrf" value="<?=\App\Core\Auth::csrf()?>"><div class="card"><div class="field"><label>Název firmy</label><input name="name" required placeholder="Např. Mai Wellness"></div><h3>Co podnikáte?</h3><p class="sub">Podle volby přizpůsobíme přehled a doporučené moduly.</p><div class="business-type-grid"><?php foreach($types as $key=>$bt): ?><label class="business-type-option"><input type="radio" name="business_type" value="<?=\App\Core\View::e($key)?>" <?=($key==='services')?'checked':''?>><span class="business-type-image"><img src="/assets/business/<?=\App\Core\View::e($bt['image'])?>" alt=""></span><span class="business-type-copy"><b><?=\App\Core\View::e($bt['name'])?></b><small><?=\App\Core\View::e($bt['intro'])?></small></span></label><?php endforeach; ?></div></div><div class="card"><div class="section-head"><div><h3>Funkce firmy</h3><p class="sub">Vyberte, které části Byznia chcete v této firmě používat. Typ podnikání vám předvybere doporučené funkce, ale výběr můžete upravit.</p></div><span class="badge ok" id="newModuleCount"></span></div><div class="module-settings-grid"><?php foreach(($module_catalog??[]) as $mk=>$mod): $checked=in_array($mk,($recommended_modules??[]),true); $core=$mk==='invoicing'; ?><label class="module-setting-option <?= $checked?'is-on':'' ?> <?= $core?'is-core':'' ?>"><input type="checkbox" name="modules[]" value="<?=\App\Core\View::e($mk)?>" <?= $checked?'checked':'' ?> <?= $core?'disabled':'' ?>><span class="module-setting-check"></span><span class="module-setting-copy"><b><?=\App\Core\View::e($mod['name'])?></b><small><?=\App\Core\View::e($mod['description'])?></small><?php if($core): ?><em>Základ Byznia</em><?php endif; ?></span></label><?php endforeach; ?></div><input type="hidden" name="modules[]" value="invoicing"><div class="module-settings-actions"><button type="button" class="btn" id="newApplyRecommended">Použít doporučené podle typu</button><span class="sub">Funkce můžete později kdykoli změnit v Nastavení.</span></div></div><div class="card"><div style="display:flex;gap:10px;align-items:center"><span class="badge ok">+ 300 Kč / měsíc</span><span class="sub">samostatné předplatné firmy</span></div><p class="sub" style="margin-top:12px">Nová firma dostane vlastní 14denní zkušební období. Po jeho skončení lze aktivovat předplatné stejně jako u první firmy.</p></div><div class="actions"><a class="btn" href="/settings">Zrušit</a><button class="btn primary">Vytvořit firmu</button></div></form>
<script>
(function(){
const form=document.querySelector('form.form');if(!form)return;
const defaults=<?php echo json_encode(array_map(fn($bt)=>$bt['modules']??[],($types??[])),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); ?>;
const moduleMap={'Zakázky':'jobs','Fakturace':'invoicing','Kalendář':'calendar','Banka':'bank','CRM':'crm','Sklad':'inventory','Dodavatelé':'received_invoices'};
const common=['reports','mail','tasks','documents'];
const boxes=[...form.querySelectorAll('input[name="modules[]"]:not([disabled])')];const radios=[...form.querySelectorAll('input[name="business_type"]')];const count=document.getElementById('newModuleCount');
function recommended(){const key=radios.find(r=>r.checked)?.value||'services';const labels=defaults[key]||[];return [...new Set(common.concat(labels.map(x=>moduleMap[x]).filter(Boolean)))];}
function update(){const n=boxes.filter(x=>x.checked).length+1;if(count)count.textContent=n+' aktivních';boxes.forEach(x=>x.closest('.module-setting-option')?.classList.toggle('is-on',x.checked));}
radios.forEach(r=>r.addEventListener('change',()=>{boxes.forEach(x=>x.checked=recommended().includes(x.value));update();}));
document.getElementById('newApplyRecommended')?.addEventListener('click',()=>{boxes.forEach(x=>x.checked=recommended().includes(x.value));update();});boxes.forEach(x=>x.addEventListener('change',update));update();
})();
</script>
<style>
.module-settings-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:16px}.module-setting-option{position:relative;display:flex;gap:12px;align-items:flex-start;border:1px solid #e5eaf2;border-radius:14px;padding:13px;background:#fff;cursor:pointer;transition:.15s}.module-setting-option:hover{border-color:#bfd3ef;background:#fbfdff}.module-setting-option.is-on{border-color:#9fc4f4;background:#f7fbff}.module-setting-option input{position:absolute;opacity:0;pointer-events:none}.module-setting-check{width:21px;height:21px;flex:0 0 21px;border:1.5px solid #b9c6d8;border-radius:6px;background:#fff;margin-top:1px;position:relative}.module-setting-option.is-on .module-setting-check{background:#1677ee;border-color:#1677ee}.module-setting-option.is-on .module-setting-check:after{content:'✓';position:absolute;inset:0;color:#fff;font-size:14px;font-weight:900;display:grid;place-items:center}.module-setting-copy{display:grid;gap:4px}.module-setting-copy b{font-size:14px}.module-setting-copy small{color:#6c7890;line-height:1.4}.module-setting-copy em{font-style:normal;font-size:10px;color:#1677ee;font-weight:800;text-transform:uppercase;letter-spacing:.05em}.module-setting-option.is-core{cursor:default}.module-settings-actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-top:16px}@media(max-width:760px){.module-settings-grid{grid-template-columns:1fr}}
</style>
