<style>
.sa-wrap{display:flex;flex-direction:column;gap:18px}.sa-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-end}.sa-head h1{margin:0}.sa-actions{display:flex;gap:8px;flex-wrap:wrap}.sa-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.sa-stat{padding:18px}.sa-stat .num{font-size:28px;font-weight:800;margin-top:5px}.sa-stat .hint{font-size:12px;color:#718096}.sa-two{display:grid;grid-template-columns:1.4fr .8fr;gap:18px}.sa-card{padding:18px}.sa-table{width:100%;border-collapse:collapse}.sa-table th,.sa-table td{padding:10px 8px;border-bottom:1px solid #e7edf5;text-align:left;vertical-align:middle}.sa-table th{font-size:12px;color:#718096}.sa-table select,.sa-table input{min-height:34px;padding:5px 8px}.sa-status{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:12px;font-weight:700;background:#eef3f8}.sa-status.ok{background:#e8f7ee}.sa-status.warn{background:#fff5dd}.sa-status.bad{background:#fdebec}.sa-mini{font-size:12px;color:#718096}.sa-card h3{margin-top:0}.sa-scroll{overflow:auto}.sa-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.sa-field label{display:block;font-size:12px;font-weight:700;color:#526174;margin-bottom:4px}.sa-field input,.sa-field select{width:100%;box-sizing:border-box}.sa-note{background:#f6f9fc;border:1px solid #e5ebf2;border-radius:12px;padding:12px;font-size:13px}.sa-link{color:inherit;text-decoration:none}.sa-link:hover{text-decoration:underline}.sa-modalish{padding-top:8px;border-top:1px solid #e7edf5;margin-top:12px}@media(max-width:1000px){.sa-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.sa-two{grid-template-columns:1fr}}@media(max-width:600px){.sa-grid{grid-template-columns:1fr}.sa-form-grid{grid-template-columns:1fr}.sa-head{align-items:flex-start;flex-direction:column}}
</style>
<div class="sa-wrap">
  <div class="sa-head">
    <div><h1 class="h">Super Admin</h1><div class="sub">Centrální správa Byznia. Přehled používání a stavů bez přístupu k zákaznickému obsahu.</div></div>
    <div class="sa-actions"><a class="btn" href="/admin/system">Systém a zdraví</a><a class="btn" href="/admin/mailboxes">Schránky</a></div>
  </div>
  <div class="sa-grid">
    <div class="card sa-stat"><div class="label">FIRMY</div><div class="num"><?=number_format((int)$stats['workspaces'],0,',',' ')?></div><div class="hint">registrovaných workspace</div></div>
    <div class="card sa-stat"><div class="label">AKTIVNÍ 30 DNÍ</div><div class="num"><?=number_format((int)$stats['active_users'],0,',',' ')?></div><div class="hint">uživatelé s přihlášením</div></div>
    <div class="card sa-stat"><div class="label">NEAKTIVNÍ</div><div class="num"><?=number_format((int)$stats['inactive_users'],0,',',' ')?></div><div class="hint">30+ dní bez přihlášení</div></div>
    <div class="card sa-stat"><div class="label">NOVÉ 30 DNÍ</div><div class="num"><?=number_format((int)$stats['new_30'],0,',',' ')?></div><div class="hint">nové firmy</div></div>
    <div class="card sa-stat"><div class="label">TRIAL</div><div class="num"><?=number_format((int)$stats['trial'],0,',',' ')?></div><div class="hint">aktuálně ve zkoušce</div></div>
    <div class="card sa-stat"><div class="label">PLATÍCÍ / FREE</div><div class="num"><?=number_format((int)$stats['paid'],0,',',' ')?></div><div class="hint">aktivní nebo ručně zdarma</div></div>
    <div class="card sa-stat"><div class="label">TRIAL DO 7 DNÍ</div><div class="num"><?=number_format((int)$stats['expiring_trial'],0,',',' ')?></div><div class="hint">vyžadují pozornost</div></div>
    <div class="card sa-stat"><div class="label">ORIENTAČNÍ MRR</div><div class="num"><?=number_format((float)$stats['mrr'],0,',',' ')?> Kč</div><div class="hint">podle nastavených cen</div></div>
  </div>
  <div class="sa-two">
    <div class="card sa-card" id="users"><h3>Zákazníci a používání</h3><div class="sub">Pouze provozní metadata: účet, stav, aktivita a využití. Žádné faktury, zákazníci ani obsah firmy.</div><div class="sa-scroll"><table class="sa-table"><thead><tr><th>Firma</th><th>Stav</th><th>Aktivita</th><th>Uživatelé</th><th>Doklady</th><th>Správa</th></tr></thead><tbody>
<?php foreach($workspaces as $w):
 $inactive=empty($w['last_activity']) || strtotime($w['last_activity'])<time()-30*86400;
 $sub=(string)($w['subscription_status']??'—');
?><tr>
<td><a class="sa-link" href="/admin/user/<?=
 (int)($w['owner_id']??0)?>"><strong><?=
 \App\Core\View::e($w['name'])?></strong></a><div class="sa-mini"><?=\App\Core\View::e($w['owner_email']??'')?></div></td>
<td><span class="sa-status <?=in_array($sub,['active','free'],true)?'ok':($sub==='trial'?'warn':'bad')?>"><?=\App\Core\View::e($sub)?></span></td>
<td><?= $inactive ? '<span class="sa-status bad">Neaktivní</span>' : '<span class="sa-status ok">Aktivní</span>' ?><div class="sa-mini"><?=\App\Core\View::e($w['last_activity']??'—')?></div></td>
<td><?=number_format((int)$w['user_count'],0,',',' ')?></td><td><?=number_format((int)$w['document_count'],0,',',' ')?></td>
<td><?php if(!empty($w['owner_id'])):?><a class="btn" href="/admin/user/<?= (int)$w['owner_id']?>">Detail</a><?php endif;?></td>
</tr><?php endforeach; ?></tbody></table></div></div>
    <div class="card sa-card"><h3>Poslední přihlášení</h3><?php foreach($recentUsers as $u): ?><div style="padding:10px 0;border-bottom:1px solid #e7edf5"><strong><?=\App\Core\View::e($u['name'])?></strong><div class="sa-mini"><?=\App\Core\View::e($u['email'])?></div><div class="sa-mini"><?=\App\Core\View::e($u['workspace_name'])?> · <?=\App\Core\View::e($u['last_login_at']??'nikdy')?></div></div><?php endforeach; ?></div>
  </div>
  <div class="card sa-card" id="all-users"><h3>Uživatelé</h3><div class="sub">Správa přístupu a rolí. Obsah firem zde není zobrazen.</div><div class="sa-scroll"><table class="sa-table"><thead><tr><th>Uživatel</th><th>Firma</th><th>Role</th><th>Stav</th><th>Poslední přihlášení</th><th>Akce</th></tr></thead><tbody><?php foreach($allUsers as $u): ?><tr><td><strong><?=\App\Core\View::e($u['name'])?></strong><div class="sa-mini"><?=\App\Core\View::e($u['email'])?></div></td><td><?=\App\Core\View::e($u['workspace_name'])?></td><td><form method="post" action="/admin/user/<?= (int)$u['id']?>/role" class="actions"><input type="hidden" name="_csrf" value="<?=\App\Core\Auth::csrf()?>"><select name="role"><option value="owner" <?=($u['role']==='owner')?'selected':''?>>Owner</option><option value="admin" <?=($u['role']==='admin')?'selected':''?>>Administrátor</option><option value="accountant" <?=($u['role']==='accountant')?'selected':''?>>Účetní</option><option value="employee" <?=($u['role']==='employee')?'selected':''?>>Zaměstnanec</option></select><button class="btn">Uložit</button></form></td><td><?=((int)$u['active'])?'<span class="sa-status ok">Aktivní</span>':'<span class="sa-status bad">Deaktivovaný</span>'?></td><td><?=\App\Core\View::e($u['last_login_at']??'nikdy')?></td><td><a class="btn" href="/admin/user/<?= (int)$u['id']?>">Detail</a> <form style="display:inline" method="post" action="/admin/user/<?= (int)$u['id']?>/toggle" onsubmit="return confirm('Opravdu změnit aktivitu účtu?')"><input type="hidden" name="_csrf" value="<?=\App\Core\Auth::csrf()?>"><button class="btn <?=((int)$u['active'])?'danger':''?>"><?=((int)$u['active'])?'Deaktivovat':'Aktivovat'?></button></form></td></tr><?php endforeach; ?></tbody></table></div></div>
  <div class="card sa-card"><h3>Co Super Admin vidí a co ne</h3><div class="sa-note"><strong>Vidí:</strong> počty, stavy účtů, předplatné, role, poslední přihlášení, provozní aktivitu a systémové zdraví. <strong>Nevidí:</strong> faktury, zákazníky, bankovní transakce, e-mailový obsah ani jiné obchodní údaje jednotlivých firem.</div></div>
</div>
