<h1 class="h">Nový doklad</h1><div class="sub">Fakturu vytvoříte bez opouštění formuláře. Zákazníka můžete vybrat, nebo ho založit přímo tady.</div>
<form class="form" method="post" id="documentForm"><input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>"><input type="hidden" name="new_customer" id="newCustomerFlag" value="0">
<div class="card customer-card"><div class="form-section-head"><div><h3 style="margin:0">Zákazník</h3><small>Existující zákazník nebo nový kontakt</small></div><button type="button" class="btn" id="newCustomerBtn">＋ Nový zákazník</button></div>
<div id="existingCustomer"><div class="field"><label>Vyberte zákazníka</label><select name="customer_id" id="customerSelect" required><option value="">Vyberte zákazníka</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>"><?=View::e($c['company_name']?:trim(($c['first_name']??'').' '.($c['last_name']??'')))?></option><?php endforeach;?></select></div></div>
<div id="newCustomerBox" class="new-customer-box" hidden><div class="new-customer-head"><b>Nový zákazník</b><button type="button" class="text-btn" id="cancelNewCustomer">Zpět na výběr</button></div><div class="row"><div class="field"><label>Firma / název</label><input name="new_customer_company" placeholder="Např. Novák s.r.o."></div><div class="field"><label>IČO</label><input name="new_customer_ico" inputmode="numeric"></div></div><div class="row"><div class="field"><label>Jméno</label><input name="new_customer_first_name"></div><div class="field"><label>Příjmení</label><input name="new_customer_last_name"></div></div><div class="row"><div class="field"><label>E-mail</label><input name="new_customer_email" type="email"></div><div class="field"><label>Telefon</label><input name="new_customer_phone"></div></div><div class="hint">Zákazník se při uložení faktury vytvoří automaticky a hned se k němu faktura připojí.</div></div></div>
<div class="row"><div class="field"><label>Typ dokladu</label><select name="doc_type"><option value="invoice">Faktura</option><option value="offer">Nabídka</option><option value="order">Objednávka</option><option value="proforma">Zálohová faktura</option><option value="credit">Dobropis</option></select></div><div class="field"><label>Datum vystavení</label><input type="date" name="issue_date" value="<?=date('Y-m-d')?>"></div></div>
<div class="row"><div class="field"><label>Splatnost</label><input type="date" name="due_date" value="<?=date('Y-m-d',strtotime('+14 days'))?>"></div><div></div></div>
<div class="card"><div style="font-weight:800;margin-bottom:12px">Položky</div><div id="items"><?php for($i=0;$i<3;$i++):?><div class="row item" style="margin-bottom:10px"><div class="field"><label>Název</label><input name="item_name[]" placeholder="Např. Konzultace"></div><div class="field"><label>Množství / jednotka</label><div style="display:flex;gap:7px"><input name="item_qty[]" type="number" step="0.01" value="1"><input name="item_unit[]" value="ks"></div></div><div class="field"><label>Jednotková cena</label><input name="item_price[]" type="number" step="0.01" value="0"></div><div class="field"><label>DPH %</label><input name="item_vat[]" type="number" step="0.01" value="21"></div></div><?php endfor;?></div><button type="button" class="btn" onclick="addItem()">+ Položka</button></div>
<button class="btn primary" type="submit">Vytvořit doklad</button></form>
<style>.form-section-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.form-section-head small{display:block;color:#728198;margin-top:4px}.new-customer-box{margin-top:14px;padding:15px;border:1px solid #dce7f3;border-radius:14px;background:#f8fbff}.new-customer-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.text-btn{border:0;background:none;color:#3970ba;font-weight:800;cursor:pointer}.hint{font-size:11px;color:#718098;margin-top:8px}.customer-card{max-width:980px}</style>
<script>
const newBtn=document.getElementById('newCustomerBtn'),cancelBtn=document.getElementById('cancelNewCustomer'),box=document.getElementById('newCustomerBox'),existing=document.getElementById('existingCustomer'),flag=document.getElementById('newCustomerFlag'),select=document.getElementById('customerSelect');
function openNewCustomer(){box.hidden=false;existing.hidden=true;flag.value='1';select.required=false;select.value='';newBtn.style.display='none';box.querySelector('input')?.focus()}
function closeNewCustomer(){box.hidden=true;existing.hidden=false;flag.value='0';select.required=true;newBtn.style.display='inline-flex'}
newBtn?.addEventListener('click',openNewCustomer);cancelBtn?.addEventListener('click',closeNewCustomer);
function addItem(){let x=document.querySelector('.item').cloneNode(true);x.querySelectorAll('input').forEach(i=>{if(i.name.includes('item_qty'))i.value=1;else if(i.name.includes('item_vat'))i.value=21;else if(i.name.includes('item_unit'))i.value='ks';else i.value=''});document.getElementById('items').appendChild(x)}
</script>