<h1 class="h">Nový doklad</h1><div class="sub">Fakturu vytvoříte bez opouštění formuláře. Zákazníka můžete vybrat, nebo ho založit přímo tady.</div>
<form class="form" method="post" action="/documents/save" id="documentForm"><input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>"><input type="hidden" name="new_customer" id="newCustomerFlag" value="0">
<div class="card customer-card"><div class="form-section-head"><div><h3 style="margin:0">Zákazník</h3><small>Existující zákazník nebo nový kontakt</small></div><button type="button" class="btn" id="newCustomerBtn">＋ Nový zákazník</button></div>
<div id="existingCustomer"><div class="field"><label>Vyberte zákazníka</label><select name="customer_id" id="customerSelect" required><option value="">Vyberte zákazníka</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>"><?=\App\Core\View::e($c['company_name']?:trim(($c['first_name']??'').' '.($c['last_name']??'')))?></option><?php endforeach;?></select></div></div>
<div id="newCustomerBox" class="new-customer-box" hidden><div class="new-customer-head"><b>Nový zákazník</b><button type="button" class="text-btn" id="cancelNewCustomer">Zpět na výběr</button></div><div class="row"><div class="field"><label>Firma / název</label><input name="new_customer_company" id="inlineAresCompany" placeholder="Např. Novák s.r.o."></div><div class="field"><label>IČO</label><div style="display:flex;gap:8px"><input name="new_customer_ico" id="inlineAresIco" inputmode="numeric"><button type="button" class="btn ares-btn" id="inlineAresBtn">Načíst z ARES</button></div><small id="inlineAresStatus" class="ares-status">IČO firmy lze načíst z ARES.</small></div></div><div class="row"><div class="field"><label>Jméno</label><input name="new_customer_first_name"></div><div class="field"><label>Příjmení</label><input name="new_customer_last_name"></div></div><div class="field"><label>DIČ</label><input name="new_customer_dic" id="inlineAresDic"></div><div class="row"><div class="field"><label>E-mail</label><input name="new_customer_email" type="email"></div><div class="field"><label>Telefon</label><input name="new_customer_phone"></div></div><div class="new-customer-address"><div class="new-customer-address-title">Fakturační adresa</div><div class="row"><div class="field"><label>Ulice a číslo</label><input name="new_customer_street" autocomplete="street-address" placeholder="Např. Dlouhá 12"></div><div class="field"><label>Město</label><input name="new_customer_city" autocomplete="address-level2" placeholder="Praha"></div></div><div class="row"><div class="field"><label>PSČ</label><input name="new_customer_zip" inputmode="numeric" autocomplete="postal-code" placeholder="110 00"></div><div></div></div></div><input type="hidden" name="new_customer_ares" id="newCustomerAresFlag" value="0"><div class="hint">Zákazník se při uložení faktury vytvoří automaticky a hned se k němu faktura připojí.</div></div></div>
<div class="row"><div class="field"><label>Typ dokladu</label><select name="doc_type"><option value="invoice" <?=($prefillDocType??'invoice')==='invoice'?'selected':''?>>Faktura</option><option value="offer" <?=($prefillDocType??'invoice')==='offer'?'selected':''?>>Nabídka</option><option value="order" <?=($prefillDocType??'invoice')==='order'?'selected':''?>>Objednávka</option><option value="proforma" <?=($prefillDocType??'invoice')==='proforma'?'selected':''?>>Zálohová faktura</option><option value="credit" <?=($prefillDocType??'invoice')==='credit'?'selected':''?>>Dobropis</option></select></div><div class="field"><label>Datum vystavení</label><input type="date" name="issue_date" value="<?=date('Y-m-d')?>"></div></div>
<div class="row"><div class="field"><label>Splatnost</label><input type="date" name="due_date" value="<?=date('Y-m-d',strtotime('+14 days'))?>"></div><div class="field"><label>Způsob úhrady</label><div class="payment-methods"><label><input type="radio" name="payment_method" value="bank_transfer" checked><span>↔ Převodem</span></label><label><input type="radio" name="payment_method" value="cash"><span>💵 Hotově</span></label><label><input type="radio" name="payment_method" value="card"><span>▣ Kartou</span></label><label><input type="radio" name="payment_method" value="gopay"><span>GoPay</span></label></div></div></div>
<div class="payment-options card"><label class="paid-toggle"><input type="checkbox" name="paid_now" value="1"><span><b>Doklad je už uhrazený</b><small>Byznio ho označí jako uhrazený a QR platbu na faktuře nezobrazí.</small></span></label></div>
<div class="card"><div style="font-weight:800;margin-bottom:12px">Položky</div><div id="items"><?php for($i=0;$i<1;$i++):?><div class="row item" style="margin-bottom:10px"><div class="field"><label>Skladová položka (volitelné)</label><select name="product_id[]"><option value="0">Bez vazby na sklad</option><?php foreach(($products??[]) as $p): ?><option value="<?=$p['id']?>"><?=\App\Core\View::e($p['name'])?> · sklad <?=\App\Core\View::e($p['stock'])?> <?=$p['unit']?></option><?php endforeach; ?></select></div><div class="field"><label>Název</label><input name="item_name[]" placeholder="Např. Konzultace nebo materiál"></div><div class="field"><label>Množství / jednotka</label><div style="display:flex;gap:7px"><input name="item_qty[]" type="number" step="0.01" value="1"><input name="item_unit[]" value="ks"></div></div><div class="field"><label>Jednotková cena</label><input name="item_price[]" type="number" step="0.01" value="0"></div><div class="field"><label>DPH %</label><input name="item_vat[]" type="number" step="0.01" value="21"></div></div><?php endfor;?></div><button type="button" class="btn" onclick="addItem()">+ Položka</button></div>
<button class="btn primary" type="submit">Vytvořit doklad</button></form>
<style>.form-section-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.form-section-head small{display:block;color:#728198;margin-top:4px}.new-customer-box{margin-top:14px;padding:15px;border:1px solid #dce7f3;border-radius:14px;background:#f8fbff}.new-customer-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.text-btn{border:0;background:none;color:#3970ba;font-weight:800;cursor:pointer}.hint{font-size:11px;color:#718098;margin-top:8px}.customer-card{max-width:980px}.new-customer-address{margin-top:14px;padding-top:14px;border-top:1px solid #dce7f3}.new-customer-address-title{font-weight:800;margin-bottom:10px}.ares-btn{white-space:nowrap;padding-inline:12px}.ares-status{display:block;color:#718098;font-size:11px;margin-top:5px}.ares-status.ok{color:#16824a}.ares-status.error{color:#b42318}.payment-methods{display:flex;flex-wrap:wrap;gap:7px}.payment-methods label{margin:0;cursor:pointer}.payment-methods input{position:absolute;opacity:0;pointer-events:none}.payment-methods span{display:block;padding:9px 11px;border:1px solid #dbe3ef;border-radius:10px;background:#fff;font-size:12px;font-weight:700;color:#52627a}.payment-methods input:checked+span{border-color:#4f46e5;background:#eef2ff;color:#3730a3}.payment-options{padding:14px 16px;margin-top:12px}.paid-toggle{display:flex;gap:10px;align-items:flex-start;cursor:pointer}.paid-toggle input{margin-top:3px}.paid-toggle small{display:block;color:#718098;font-weight:400;margin-top:3px}.paid-toggle b{font-size:13px}</style>
<script>
const newBtn=document.getElementById('newCustomerBtn'),cancelBtn=document.getElementById('cancelNewCustomer'),box=document.getElementById('newCustomerBox'),existing=document.getElementById('existingCustomer'),flag=document.getElementById('newCustomerFlag'),select=document.getElementById('customerSelect');
function openNewCustomer(){box.hidden=false;existing.hidden=true;flag.value='1';select.required=false;select.value='';newBtn.style.display='none';box.querySelector('input')?.focus()}
function closeNewCustomer(){box.hidden=true;existing.hidden=false;flag.value='0';select.required=true;newBtn.style.display='inline-flex'}
newBtn?.addEventListener('click',openNewCustomer);cancelBtn?.addEventListener('click',closeNewCustomer);
const aresBtn=document.getElementById('inlineAresBtn'),aresIco=document.getElementById('inlineAresIco'),aresStatus=document.getElementById('inlineAresStatus'),aresFlag=document.getElementById('newCustomerAresFlag');
async function loadInlineAres(){const ico=(aresIco?.value||'').replace(/\D/g,'');if(aresIco)aresIco.value=ico;if(ico.length!==8){if(aresStatus){aresStatus.textContent='IČO musí mít 8 číslic.';aresStatus.className='ares-status error'}return}aresBtn.disabled=true;aresBtn.textContent='Načítám…';try{const fd=new FormData();fd.append('_csrf',document.querySelector('input[name="_csrf"]')?.value||'');fd.append('ico',ico);const r=await fetch('/customers/ares',{method:'POST',body:fd,headers:{'X-Requested-With':'XMLHttpRequest'}});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'ARES se nepodařilo načíst.');const d=j.data||{};const set=(id,v)=>{const el=document.getElementById(id);if(el&&v!==undefined)el.value=v||''};set('inlineAresCompany',d.company_name);set('inlineAresDic',d.dic);set('new_customer_street',d.street);set('new_customer_city',d.city);set('new_customer_zip',d.zip);if(aresFlag)aresFlag.value='1';if(aresStatus){aresStatus.textContent='Údaje z ARES načteny.';aresStatus.className='ares-status ok'}}catch(e){if(aresStatus){aresStatus.textContent=e.message;aresStatus.className='ares-status error'}}finally{aresBtn.disabled=false;aresBtn.textContent='Načíst z ARES'}}aresBtn?.addEventListener('click',loadInlineAres);
function addItem(){let x=document.querySelector('.item').cloneNode(true);x.querySelectorAll('input').forEach(i=>{if(i.name.includes('item_qty'))i.value=1;else if(i.name.includes('item_vat'))i.value=21;else if(i.name.includes('item_unit'))i.value='ks';else if(i.name.includes('product_id'))i.value='0';else i.value=''});document.getElementById('items').appendChild(x)}
</script>