<?php $sentId=(int)($_GET['sent']??0); ?>
<div class="page-head"><div><h1>Doklady</h1><div class="sub">Faktury, zálohové faktury, nabídky, objednávky a dobropisy.</div></div><div class="actions doc-create-actions"><a class="btn primary" href="/documents/new?type=invoice">+ Faktura</a><a class="btn" href="/documents/new?type=proforma">+ Zálohová</a><a class="btn" href="/documents/new?type=offer">+ Nabídka</a><a class="btn" href="/documents/new?type=order">+ Objednávka</a><a class="btn" href="/documents/new?type=credit">+ Dobropis</a></div></div>
<?php if($sentId): ?><div class="notice success">E-mail k dokladu byl odeslán zákazníkovi.</div><?php endif; ?>
<div class="card tablewrap"><table class="table"><tr><th>Číslo</th><th>Zákazník</th><th>Typ</th><th>Datum</th><th>Splatnost</th><th>Stav</th><th>Celkem</th><th>Akce</th></tr>
<?php foreach($documents as $d): ?>
<tr>
<td><b><?=\App\Core\View::e($d['doc_number'])?></b></td>
<td><?=\App\Core\View::e($d['company_name']?:trim(($d['first_name']??'').' '.($d['last_name']??'')))?></td>
<td><?=\App\Core\View::e(['invoice'=>'Faktura','proforma'=>'Zálohová faktura','offer'=>'Nabídka','order'=>'Objednávka','credit'=>'Dobropis'][$d['doc_type']]??$d['doc_type'])?></td>
<td><?=\App\Core\View::e($d['issue_date'])?></td><td><?=\App\Core\View::e($d['due_date'])?></td>
<td><span class="badge <?=$d['payment_status']==='paid'?'ok':($d['payment_status']==='unpaid'?'warn':'')?>"><?=\App\Core\View::e($d['payment_status'])?></span></td>
<td><?=\App\Core\View::money($d['total_with_vat'])?></td>
<td class="doc-actions"><a class="btn" href="/documents/<?=$d['id']?>/pdf">PDF</a><a class="btn" href="/documents/<?=$d['id']?>/isdoc">ISDOC</a>
<button type="button" class="btn primary send-doc" data-id="<?=$d['id']?>" data-email="<?=\App\Core\View::e($d['email']??'')?>" data-type="<?=\App\Core\View::e($d['doc_type'])?>" data-number="<?=\App\Core\View::e($d['doc_number'])?>">Odeslat zákazníkovi</button>
<?php if($d['doc_type']=='invoice'): ?><a class="btn" href="/documents/<?=$d['id']?>/qr" target="_blank" rel="noopener">QR</a><?php endif; ?>
<?php if($d['doc_type']==='invoice' && $d['status']!=='cancelled' && $d['payment_status']!=='paid'): ?><button type="button" class="btn primary pay-doc" data-id="<?=$d['id']?>" data-number="<?=App\Core\View::e($d['doc_number'])?>" data-total="<?=App\Core\View::e((string)$d['total_with_vat'])?>" data-paid="<?=App\Core\View::e((string)($d['paid_amount']??0))?>">Zaznamenat platbu</button><?php endif; ?>
<?php if($d['doc_type']=='invoice' && $d['status']!=='cancelled'): ?><form method="post" action="/documents/<?=$d['id']?>/cancel" style="display:inline"><input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>"><button class="btn" onclick="return confirm('Opravdu stornovat doklad?')">Storno</button></form><?php endif; ?>
<?php if($d['doc_type']==='offer'): ?><form method="post" action="/documents/<?=$d['id']?>/offer-status" style="display:inline"><input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>"><select name="status" onchange="this.form.submit()"><option value="pending" <?=($d['status']==='pending')?'selected':''?>>Čeká</option><option value="accepted" <?=($d['status']==='accepted')?'selected':''?>>Schváleno</option><option value="rejected" <?=($d['status']==='rejected')?'selected':''?>>Zamítnuto</option></select></form><form method="post" action="/documents/<?=$d['id']?>/convert-job" style="display:inline"><input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>"><button class="btn">→ Zakázka</button></form><?php endif; ?>
</td></tr>
<?php endforeach; if(!$documents): ?><tr><td colspan="8" class="sub">Zatím nemáte žádné doklady.</td></tr><?php endif; ?></table></div>
<div id="payModal" class="doc-mail-modal" hidden><div class="doc-mail-backdrop" data-close-pay></div><div class="doc-mail-card"><div class="doc-mail-head"><div><h2>Zaznamenat platbu</h2><div class="sub" id="payMeta"></div></div><button type="button" class="text-btn" data-close-pay>✕</button></div><form method="post" id="payForm"><input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>"><label>Částka</label><input type="number" name="amount" id="payAmount" min="0.01" step="0.01" required><label>Datum úhrady</label><input type="date" name="paid_at" id="payDate" value="<?=date('Y-m-d')?>" required><label>Způsob úhrady</label><select name="method" id="payMethod"><option value="bank">Bankovní převod</option><option value="cash">Hotově</option><option value="card">Kartou</option><option value="other">Jiné</option></select><div class="mail-note">Lze zadat i částečnou úhradu. Zbývající částka zůstane na faktuře.</div><div class="doc-mail-actions"><button type="button" class="btn" data-close-pay>Zrušit</button><button class="btn primary" type="submit">Uložit platbu</button></div></form></div></div><div id="sendModal" class="doc-mail-modal" hidden><div class="doc-mail-backdrop" data-close-mail></div><div class="doc-mail-card"><div class="doc-mail-head"><div><h2>Odeslat zákazníkovi</h2><div class="sub" id="mailMeta"></div></div><button type="button" class="text-btn" data-close-mail>✕</button></div><form method="post" id="sendMailForm"><input type="hidden" name="_csrf" value="<?=\App\Core\Auth::csrf()?>"><label>Předmět</label><input name="subject" id="mailSubject" required><label>Text e-mailu</label><textarea name="body" id="mailBody" rows="13" required></textarea><div class="mail-note">PDF dokladu bude přiloženo automaticky. Před odesláním můžeš text upravit.</div><div class="doc-mail-actions"><button type="button" class="btn" data-close-mail>Zrušit</button><button class="btn primary" type="submit">Odeslat e-mail</button></div></form></div></div>
<style>
.doc-create-actions{display:flex;flex-wrap:wrap;gap:8px;justify-content:flex-end}.doc-create-actions .btn{white-space:nowrap}.notice.success{margin:0 0 16px;padding:12px 16px;border-radius:12px;background:#ecfdf3;color:#137333;font-weight:700}.doc-actions{white-space:normal;min-width:300px}.doc-actions .btn,.doc-actions form,.doc-actions select{margin:3px}.doc-mail-modal[hidden]{display:none}.doc-mail-modal{position:fixed;inset:0;z-index:9999;overflow:auto;padding:16px}.doc-mail-backdrop{position:absolute;inset:0;background:rgba(7,20,45,.45);backdrop-filter:blur(3px)}.doc-mail-card{position:relative;width:min(720px,100%);max-height:calc(100dvh - 32px);margin:4vh auto 0;background:#fff;border-radius:20px;padding:24px;box-shadow:0 25px 70px rgba(10,30,70,.25);overflow:auto}.doc-mail-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:14px}.doc-mail-card h2{margin:0 0 5px}.doc-mail-card label{display:block;font-weight:800;margin:10px 0 6px}.doc-mail-card input,.doc-mail-card textarea{width:100%;box-sizing:border-box;border:1px solid #d8e1ee;border-radius:12px;padding:10px 12px;font:inherit}.doc-mail-card textarea{resize:vertical;line-height:1.5;min-height:180px;max-height:38dvh}.mail-note{font-size:12px;color:#718096;margin-top:8px}.doc-mail-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px;position:sticky;bottom:-1px;background:#fff;padding-top:10px}.doc-mail-actions .btn{min-width:130px}@media(max-width:760px){.doc-create-actions{justify-content:flex-start}.doc-actions{min-width:0}.doc-mail-modal{padding:8px}.doc-mail-card{width:100%;max-height:calc(100dvh - 16px);margin:0;padding:16px;border-radius:16px}.doc-mail-card textarea{min-height:120px;max-height:30dvh}.doc-mail-actions{display:grid;grid-template-columns:1fr 1fr}.doc-mail-actions .btn{width:100%;min-width:0}.doc-mail-head{margin-bottom:8px}.doc-mail-card h2{font-size:20px}}@media(max-width:430px){.doc-mail-actions{grid-template-columns:1fr}.doc-mail-card textarea{max-height:26dvh}}
</style>
<script>
(()=>{const modal=document.getElementById('payModal'),form=document.getElementById('payForm'),amount=document.getElementById('payAmount'),meta=document.getElementById('payMeta');
document.querySelectorAll('.pay-doc').forEach(b=>b.addEventListener('click',()=>{const total=parseFloat(b.dataset.total||'0'),paid=parseFloat(b.dataset.paid||'0'),remaining=Math.max(0,total-paid);form.action='/documents/'+b.dataset.id+'/pay';amount.value=remaining.toFixed(2);amount.max=remaining.toFixed(2);meta.textContent='Faktura '+b.dataset.number+' · zbývá '+remaining.toFixed(2)+' Kč';modal.hidden=false;}));
document.querySelectorAll('[data-close-pay]').forEach(x=>x.addEventListener('click',()=>modal.hidden=true));
})();
</script>
<script>
(()=>{const modal=document.getElementById('sendModal'),form=document.getElementById('sendMailForm'),subject=document.getElementById('mailSubject'),body=document.getElementById('mailBody'),meta=document.getElementById('mailMeta');
const templates={invoice:['Faktura','Dobrý den,\n\nv příloze Vám zasíláme fakturu.\n\nS pozdravem,'],proforma:['Zálohová faktura','Dobrý den,\n\nv příloze Vám zasíláme zálohovou fakturu.\n\nS pozdravem,'],offer:['Nabídka','Dobrý den,\n\nv příloze Vám zasíláme nabídku.\n\nS pozdravem,'],order:['Objednávka','Dobrý den,\n\nv příloze Vám zasíláme objednávku.\n\nS pozdravem,'],credit:['Dobropis','Dobrý den,\n\nv příloze Vám zasíláme dobropis.\n\nS pozdravem,']};
document.querySelectorAll('.send-doc').forEach(b=>b.addEventListener('click',()=>{const t=templates[b.dataset.type]||['Doklad','Dobrý den,\n\nv příloze Vám zasíláme doklad.\n\nS pozdravem,'];const num=b.dataset.number;subject.value=t[0]+' č. '+num+' – Byznio';body.value=t[1]+'\nByznio';meta.textContent='Doklad '+num+(b.dataset.email?' · '+b.dataset.email:' · zákazník nemá vyplněný e-mail');form.action='/documents/'+b.dataset.id+'/send-email';modal.hidden=false;}));
document.querySelectorAll('[data-close-mail]').forEach(x=>x.addEventListener('click',()=>modal.hidden=true));
})();
</script>
