<?php $sentId=(int)($_GET['sent']??0); ?>
<div class="page-head"><div><h1>Doklady</h1><div class="sub">Faktury, zálohové faktury, nabídky, objednávky a dobropisy.</div></div></div>
<?php if($sentId): ?><div class="notice success">E-mail k dokladu byl odeslán zákazníkovi.</div><?php endif; ?>
<div class="card tablewrap"><table class="table"><tr><th>Číslo</th><th>Zákazník</th><th>Typ</th><th>Datum</th><th>Splatnost</th><th>Stav</th><th>Celkem</th><th>Akce</th></tr>
<?php foreach($documents as $d): ?>
<tr>
<td><b><?=\App\Core\View::e($d['doc_number'])?></b></td>
<td><?=\App\Core\View::e($d['company_name']?:trim(($d['first_name']??'').' '.($d['last_name']??'')))?></td>
<td><?=\App\Core\View::e(['invoice'=>'Faktura','proforma'=>'Zálohová faktura','offer'=>'Nabídka','order'=>'Objednávka','credit'=>'Dobropis'][$d['doc_type']]??$d['doc_type'])?></td>
<td><?=\App\Core\View::e($d['issue_date'])?></td><td><?=\App\Core\View::e($d['due_date'])?></td>
<td><span class="badge <?=$d['payment_status']==='paid'?'ok':($d['payment_status']==='unpaid'?'warn':'')?>"><?=\App\Core\View::e($d['payment_status'])?></span></td>
<td><?=\App\Core\View::money($d['total_with_vat'])?></td>
<td class="doc-actions"><a class="btn" href="/documents/<?=$d['id']?>/pdf">PDF</a><a class="btn" href="/documents/<?=$d['id']?>/isdoc">ISDOC</a>
<button type="button" class="btn primary send-doc" data-id="<?=$d['id']?>" data-email="<?=\App\Core\View::e($d['email']??'')?>" data-type="<?=\App\Core\View::e($d['doc_type'])?>" data-number="<?=\App\Core\View::e($d['doc_number'])?>">Odeslat zákazníkovi</button>
<?php if($d['doc_type']=='invoice'): ?><a class="btn" href="/documents/<?=$d['id']?>/qr" target="_blank" rel="noopener">QR</a><?php endif; ?>
<?php if($d['doc_type']=='invoice' && $d['status']!=='cancelled'): ?><form method="post" action="/documents/<?=$d['id']?>/cancel" style="display:inline"><input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>"><button class="btn" onclick="return confirm('Opravdu stornovat doklad?')">Storno</button></form><?php endif; ?>
<?php if($d['doc_type']==='offer'): ?><form method="post" action="/documents/<?=$d['id']?>/offer-status" style="display:inline"><input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>"><select name="status" onchange="this.form.submit()"><option value="pending" <?=($d['status']==='pending')?'selected':''?>>Čeká</option><option value="accepted" <?=($d['status']==='accepted')?'selected':''?>>Schváleno</option><option value="rejected" <?=($d['status']==='rejected')?'selected':''?>>Zamítnuto</option></select></form><form method="post" action="/documents/<?=$d['id']?>/convert-job" style="display:inline"><input type="hidden" name="_csrf" value="<?=App\Core\Auth::csrf()?>"><button class="btn">→ Zakázka</button></form><?php endif; ?>
</td></tr>
<?php endforeach; if(!$documents): ?><tr><td colspan="8" class="sub">Zatím nemáte žádné doklady.</td></tr><?php endif; ?></table></div>
<div id="sendModal" class="doc-mail-modal" hidden><div class="doc-mail-backdrop" data-close-mail></div><div class="doc-mail-card"><div class="doc-mail-head"><div><h2>Odeslat zákazníkovi</h2><div class="sub" id="mailMeta"></div></div><button type="button" class="text-btn" data-close-mail>✕</button></div><form method="post" id="sendMailForm"><input type="hidden" name="_csrf" value="<?=\App\Core\Auth::csrf()?>"><label>Předmět</label><input name="subject" id="mailSubject" required><label>Text e-mailu</label><textarea name="body" id="mailBody" rows="13" required></textarea><div class="mail-note">PDF dokladu bude přiloženo automaticky. Před odesláním můžeš text upravit.</div><div class="doc-mail-actions"><button type="button" class="btn" data-close-mail>Zrušit</button><button class="btn primary" type="submit">Odeslat e-mail</button></div></form></div></div>
<style>
.notice.success{margin:0 0 16px;padding:12px 16px;border-radius:12px;background:#ecfdf3;color:#137333;font-weight:700}.doc-actions{white-space:normal;min-width:300px}.doc-actions .btn,.doc-actions form,.doc-actions select{margin:3px}.doc-mail-modal[hidden]{display:none}.doc-mail-modal{position:fixed;inset:0;z-index:9999}.doc-mail-backdrop{position:absolute;inset:0;background:rgba(7,20,45,.45);backdrop-filter:blur(3px)}.doc-mail-card{position:relative;width:min(720px,calc(100% - 28px));margin:7vh auto 0;background:#fff;border-radius:20px;padding:24px;box-shadow:0 25px 70px rgba(10,30,70,.25)}.doc-mail-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.doc-mail-card h2{margin:0 0 5px}.doc-mail-card label{display:block;font-weight:800;margin:12px 0 6px}.doc-mail-card input,.doc-mail-card textarea{width:100%;box-sizing:border-box;border:1px solid #d8e1ee;border-radius:12px;padding:11px 12px;font:inherit}.doc-mail-card textarea{resize:vertical;line-height:1.55}.mail-note{font-size:12px;color:#718096;margin-top:8px}.doc-mail-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}@media(max-width:760px){.doc-actions{min-width:0}.doc-mail-card{margin-top:3vh;padding:18px}}
</style>
<script>
(()=>{const modal=document.getElementById('sendModal'),form=document.getElementById('sendMailForm'),subject=document.getElementById('mailSubject'),body=document.getElementById('mailBody'),meta=document.getElementById('mailMeta');
const templates={invoice:['Faktura','Dobrý den,\n\nv příloze Vám zasíláme fakturu.\n\nS pozdravem,'],proforma:['Zálohová faktura','Dobrý den,\n\nv příloze Vám zasíláme zálohovou fakturu.\n\nS pozdravem,'],offer:['Nabídka','Dobrý den,\n\nv příloze Vám zasíláme nabídku.\n\nS pozdravem,'],order:['Objednávka','Dobrý den,\n\nv příloze Vám zasíláme objednávku.\n\nS pozdravem,'],credit:['Dobropis','Dobrý den,\n\nv příloze Vám zasíláme dobropis.\n\nS pozdravem,']};
document.querySelectorAll('.send-doc').forEach(b=>b.addEventListener('click',()=>{const t=templates[b.dataset.type]||['Doklad','Dobrý den,\n\nv příloze Vám zasíláme doklad.\n\nS pozdravem,'];const num=b.dataset.number;subject.value=t[0]+' č. '+num+' – Byznio';body.value=t[1]+'\nByznio';meta.textContent='Doklad '+num+(b.dataset.email?' · '+b.dataset.email:' · zákazník nemá vyplněný e-mail');form.action='/documents/'+b.dataset.id+'/send-email';modal.hidden=false;}));
document.querySelectorAll('[data-close-mail]').forEach(x=>x.addEventListener('click',()=>modal.hidden=true));
})();
</script>
