<?php
$r=$report;$m=fn($v)=>\App\Core\View::money($v);$cf=(float)$r['cashflow'];$cfClass=$cf>=0?'ok':'danger';
$periodName=$kind==='month'?'Měsíční přehled':'Týdenní přehled'; $mods=$enabled_modules??[]; $catalog=$module_catalog??[];
?>
<div class="page-head"><div><div class="eyebrow">BYZNIO INTELIGENCE</div><h1><?=\App\Core\View::e($periodName)?></h1><div class="sub"><?=\App\Core\View::e($r['start'])?> – <?=\App\Core\View::e($r['end'])?> · <?=\App\Core\View::e($r['bt']['name'])?></div></div><div class="report-periods"><a class="btn <?=$kind==='week'?'primary':''?>" href="/reports?period=week">Týden</a><a class="btn <?=$kind==='month'?'primary':''?>" href="/reports?period=month">Měsíc</a></div></div>
<section class="report-hero card"><div><span class="report-kicker">JAK NA TOM JSTE</span><h2>Byznio vám skládá čísla dohromady.</h2><p><?=\App\Core\View::e($r['bt']['intro'])?></p></div><span class="report-business-image"><img src="/assets/business/<?=\App\Core\View::e($r['bt']['image'])?>" alt=""></span></section>
<div class="report-grid">
<a class="report-card card" href="/documents"><small>Vystaveno</small><strong><?=$m($r['invoiceIssued'])?></strong><span><?=$r['invoiceCount']?> faktur · <?=$r['paidInvoiceCount']?> uhrazených</span></a>
<?php if(in_array('bank',$mods,true)): ?><a class="report-card card" href="/bank"><small>Přijato</small><strong><?=$m($r['received'])?></strong><span>Skutečně zaevidované úhrady v období</span></a><?php endif; ?>
<?php if(in_array('expenses',$mods,true)): ?><a class="report-card card" href="/expenses"><small>Výdaje</small><strong><?=$m($r['expenses'])?></strong><span>Evidované náklady v období</span></a><?php endif; ?>
<?php if(in_array('bank',$mods,true)||in_array('expenses',$mods,true)): ?><a class="report-card card <?=$cfClass?>" href="<?=in_array('bank',$mods,true)?'/bank':'/expenses'?>"><small>Cash flow z období</small><strong><?=$cf>=0?'+':''?><?=$m($cf)?></strong><span><?=$r['bankCount']?'Podle bankovních pohybů':'Podle evidovaných příjmů a výdajů'?></span></a><?php endif; ?>
<a class="report-card card warn" href="/documents"><small>Neuhrazené vystavené faktury</small><strong><?=$m($r['receivables'])?></strong><span>Po splatnosti <?=$m($r['overdue'])?></span></a>
<?php if(in_array('received_invoices',$mods,true)): ?><a class="report-card card warn" href="/received-invoices"><small>Neuhrazené přijaté faktury</small><strong><?=$m($r['receivedInvoices'])?></strong><span><?=$r['dueReceivedOverdue']?> po splatnosti · <?=$r['dueReceivedCount']?> v období</span></a><?php endif; ?>
</div>
<section class="report-two">
<?php if(in_array('inventory',$mods,true)): ?><div class="card report-section"><div class="section-head"><div><span class="report-kicker">SKLAD</span><h3>Kolik máte uvnitř firmy</h3></div><a href="/products" class="btn">Otevřít sklad</a></div><div class="stock-summary"><div><b><?=$m($r['stock'])?></b><small>hodnota skladu</small></div><div><b><?=$r['products']?></b><small>aktivních položek</small></div><div><b><?=$r['low']?></b><small>na minimální zásobě</small></div></div><?php if($r['topStock']): ?><div class="mini-table"><?php foreach($r['topStock'] as $p): ?><div><span><?=\App\Core\View::e($p['name'])?></span><span><?=\App\Core\View::e($p['stock'])?> <?=\App\Core\View::e($p['unit'])?></span><b><?=$m($p['value'])?></b></div><?php endforeach; ?></div><?php else: ?><div class="report-empty">Ve skladu zatím nejsou evidované položky.</div><?php endif; ?></div><?php endif; ?>
<div class="card report-section"><div class="section-head"><div><span class="report-kicker">CO TEĎ</span><h3>Byznio doporučuje</h3></div></div><div class="recommend-list"><?php if($r['overdue']>0): ?><div class="recommend danger"><b>Máte <?=$r['dueReceivedOverdue']+$r['dueReceivedCount']?> otevřených závazků a <?=$m($r['overdue'])?> pohledávek po splatnosti.</b><span>Projděte upomínky a přijaté faktury.</span></div><?php endif; ?><?php if($r['low']>0): ?><div class="recommend"><b><?=$r['low']?> položek je na minimální zásobě.</b><span>Otevřete sklad a zkontrolujte, co je potřeba objednat.</span></div><?php endif; ?><?php if($cf<0): ?><div class="recommend danger"><b>Cash flow z období je v minusu <?=$m(abs($cf))?>.</b><span>Největší tlak tvoří rozdíl mezi skutečnými příjmy a výdaji.</span></div><?php endif; ?><?php if($r['overdue']==0 && $r['low']==0 && $cf>=0): ?><div class="recommend ok"><b>Čísla vypadají klidně.</b><span>Pokračujte ve sledování pohledávek, závazků a cash flow.</span></div><?php endif; ?></div></div>
</section>
<section class="card report-business"><div class="section-head"><div><span class="report-kicker">VÁŠ TYP PODNIKÁNÍ</span><h3><?=\App\Core\View::e($r['bt']['name'])?></h3><p><?=\App\Core\View::e($r['bt']['intro'])?></p></div><a href="/settings" class="btn">Upravit typ</a></div><div class="module-pills"><?php foreach($mods as $mk): if(isset($catalog[$mk])): ?><span><?=\App\Core\View::e($catalog[$mk]['name'])?></span><?php endif; endforeach; ?></div></section>
